### ISSUE TITLE
how can I find the  touch point in the bitmap 

### ISSUE THREAD

**Issue by joyoyao** [alexvasilkov/GestureViews#10]
i use GestureViews
when my  finger touch the phone screen
i want to find the  touch point in the bitmap  ;
Could you  help me

**Comment by alexvasilkov** [comment]
Probably you want something similar to what is done in [GestureFrameLayout.dispatchTouchEvent()](https://github.com/alexvasilkov/GestureViews/blob/master/library/src/main/java/com/alexvasilkov/gestures/views/GestureFrameLayout.java#L87).

**Comment by joyoyao** [comment]
thanks
