### ISSUE TITLE
Double tap fires zoom gestures

### ISSUE THREAD

**Issue by neestell** [alexvasilkov/GestureViews#100]
Hello, Alex
I have found an unpredictable behavior in case user tap twice very fast and hold finger on the screen, therefore, photo zoom in/out if you drag a finger. Hope it help.
Thanks

**Comment by alexvasilkov** [comment]
That's called "quick scale", see [Android docs](https://developer.android.com/reference/android/view/ScaleGestureDetector.html#setQuickScaleEnabled(boolean)).
