### ISSUE TITLE
Unable to reset state / zoom

### ISSUE THREAD

**Issue by ParticleCore** [alexvasilkov/GestureViews#101]
I am currently using this with Picasso and I am having a problem when switching between images that are smaller than the screen and images that are larger.

The problem is as follows, using GestureFrameLayout with a single ImageView inside. All images are loaded inside that same imageview, there are no pagers:

 - When loading an image larger than the screen it adjusts correctly to the screen bounds.
 - After that, when changing to an image that is smaller than the screen (same imageview as before) it adjusts its size correctly, but its zoom is set to the max. So far so good.
 - The problem comes now when I load another image that is larger than the screen because it loads at max zoom, since the previous image left the GestureView with the current zoom at max.

None of this would be a problem if there is a method available to reset the gesture view before loading a new image, but I have already tried for over a week to find it and hack it, but so far there has been nothing that can reset the gesture view as if there has been no image loaded before.

I tried resetState, changing the zoom programatically, etc. Nothing works, the larger images are always zoomed in if the previously loaded image was an image smaller than the screen.

The only thing that works is to completely destroy the gesture view and inflate it again, but this is not a valid solution for the case I have.

Is there any way to fix this or to do this properly? The documentation is lacking any insight on this aspect and other than scavenging the source code, I cannot find anything else that might solve this problem.

**Comment by alexvasilkov** [comment]
If you are using regular ImageView inside GestureFrameLayout then your problem is most probably not with this library. But it is not completely clear from your description, so please provide your layout structure.

State reset: `GestureController#resetState()` should work fine actually (it resets state to initial values), you can check it in sample app in "Layout viewer" example - when changing any settings in action bar menu `resetState` method will be called.
But again, I think you have problems with regular ImageView not with this library, so please provide more details.

**Comment by ParticleCore** [comment]
Yes, it is indeed a regular ImageView, shouldn't it be? I followed the documentation example: 

>

https://github.com/alexvasilkov/GestureViews/wiki/Usage

And I do only have one child, the ImageView.

Also the reset state is not working as expected because it appears that the previous state "lingers" for quite a lot of time since no matter when I execute the reset state it remains zoomed in. Debugging shows that the image state (min zoom, max zoom, etc.) is still the same from the previous image. In fact, the only value that is really updated as soon as the image is changed is the deprecated `getEffectiveMinZoom` (and I assume the equivalent max is also updated)

https://github.com/alexvasilkov/GestureViews/blob/7c7890954b49fb84665d6f23ba00fe21b245b273/library/src/main/java/com/alexvasilkov/gestures/StateController.java#L341-L349

I have even tested tried resetting the state with a Runnable and it still kept the previous state for quite some time, I was only able to correctly reset the state after the new image loaded by running a runnable with a 2s delay, otherwise the state would never be updated according to the new image size.

It feels like a very extreme async state method is being used, to the point of rendering the reset state absolutely useless when loading a new image inside the ImageView.

**Comment by alexvasilkov** [comment]
If you only need to show single image then you should use `GestureImageView` as shown in wiki. `GestureFrameLayout` is intended for cases when you need to control a bunch of views at once.

Note that you still don't provide any code/layouts so I can't help you here. From what I understand you probably have some problems with your layout setup. There is no async code in the library, in fact you should only use lib's API from UI thread as with any other Android views.

If you have troubles setting up `GestureImageView` check examples from [sample app](https://github.com/alexvasilkov/GestureViews/tree/master/sample) and specifically [Image viewer](https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/ex/image/viewer/ImageViewerActivity.java) example.

**Comment by ParticleCore** [comment]
I will then use the `GestureImageView` as advised and see if the problems I found are resolved. Closing for now, will re open if the problems persist after testing.  Thanks, Alex.
