### ISSUE TITLE
DoubleTap zoomOut return wrong minZoom state

### ISSUE THREAD

**Issue by XJIOP** [alexvasilkov/GestureViews#102]
When open some images, zoom is e.g 0.41634542 after doubleTap zoomOut in onStateChanged return zoom state 0.41634536 and it is hard to check when image has zoomed out.

**Comment by alexvasilkov** [comment]
That's how floating math works, nothing we can do about it, but you can use `State#equals(float, float)` and `State#compare(float, float)` to compare floats with decreased accuracy.

**Comment by XJIOP** [comment]
State#equals(float, float) works fine! Thanks!
