### ISSUE TITLE
Trying to draw too large

### ISSUE THREAD

**Issue by vishalvaghani** [alexvasilkov/GestureViews#103]
Can you help out for this issue.
open image then crash the app

Log :-

Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(113598720bytes) bitmap.
       at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
       at android.graphics.Canvas.drawBitmap(Canvas.java:1415)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:528)
       at android.widget.ImageView.onDraw(ImageView.java:1316)
       at android.view.View.draw(View.java:17185)

**Comment by alexvasilkov** [comment]
You are trying to load too big image. This library does not handle images scaling so you should rely on 3rd party images loading libraries (like Glide or Picasso) to scale them down.

**Comment by vishalvaghani** [comment]
hi alexvasilkov, it can give error on android 7 only

**Comment by alexvasilkov** [comment]
Ok, but still, I can't see how is it connected to the library, it does not do any rendering, instead it relies on ImageView to render and on 3rd party libs to load images.

Does not seems like I can help you here.

**Comment by vishalvaghani** [comment]
It okay,
i have use glide to load image.

**Comment by lohrasbii** [comment]
I am facing this issue and I see too many app crashes in firebase crashlyticts panel.
I checked logs and found that images that causes crashes have not big size. They have size smaller than 300KB and max image size in pixel is 500*300

**Comment by lohrasbii** [comment]
Maybe this happens when user try too full zooming on image.

**Comment by alexvasilkov** [comment]
Please check [this Glide issue](https://github.com/bumptech/glide/issues/3775), can it be the case?

Note that this library does not modify bitmaps in any way, so if error says that bitmap size is "113598720 bytes" it means that this is the size of the image that was loaded into GestureImageView and it just cannot be rendered.

This library relies on image matrix and should not crash regardless of zoom level, unless the bitmap is actually huge.
