### ISSUE TITLE
Load a picture in GestureImageView size(9000x1080) can't show

### ISSUE THREAD

**Issue by yiranchunxi** [alexvasilkov/GestureViews#108]
picture url  "http://221.180.167.138/lngh_img/circle/landscape/detail/6f27b76bcfe1c19a49c3fd082a3708b6"
debug info  W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (9000x1080, max=8192x8192)
thanks !

**Comment by alexvasilkov** [comment]
This library does not handle images loading, so you should peek external libs to load the images (and resize them if necessary). If you really need to display huge images then you can try this library: https://github.com/davemorrissey/subsampling-scale-image-view.

Note though, that in most cases you should better size down your images, 9000x1080 is way too big for mobile users.
