### ISSUE TITLE
Force recheck setFitMethod after changing MovementArea

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#11]
I'm using something like following

    cropImageGestureView.getController().getSettings()
                .setFitMethod(Settings.Fit.OUTSIDE)
                .setFillViewport(true)
                .setRotationEnabled(true);

Then somewhere in the code I change the `MovementArea` and then it happens, that the fill method is not applied until I touch the `PhotoView` again. Code looks like following:

    cropImageGestureView.getController().getSettings()
                    .setMovementArea(w, h);

How can I force to update the image scaling to fulfill the fit method again without touching the `PhotoView`?

I want to ONLY update if the current scaling of the image does not fulfill the fit method restrictions. `cropImageGestureView.getController().resetState();` will work but resets the scaling, can I somehow force the checking of the restrictions?

PS: this is important for me as I allow to specify crop ratio by the user. And I allow to freely scale my overlay view, so the image underneath should not rescale as long as it's bigger than the current overlay region...

**Comment by alexvasilkov** [comment]
You can try `getController().updateState();` but it will not correctly update zoom levels.
To update zoom levels you would need to call `getController().getStateController().adjustZoomLevels(getController().getState())`. But unfortunately `adjustZoomLevels()` method is private.

Can you try to call `adjustZoomLevels()` through reflection and than call `updateState()`, does it help to achieve what you want? If yes, I will think how to make this API public.

**Comment by MFlisar** [comment]
`updateState` does not work, I saw that method and tried it already...

I will try your suggestion and tell you if it works. Thanks for the help

**Comment by MFlisar** [comment]
Thanks for the help, got it working. Following seems to work quite well:

    cropImageGestureView.getController().getSettings()
                .setMovementArea(w, h);
        
        // cropImageGestureView.getController().resetState();
        // update zoom level
        try
        {
            Method method = StateController.class.getDeclaredMethod("adjustZoomLevels", State.class);
            method.setAccessible(true);
            Object updated = method.invoke(cropImageGestureView.getController().getStateController(), cropImageGestureView.getController().getState());
            if (updated != null && ((Boolean)updated))
                cropImageGestureView.getController().updateState();
        }
        catch (NoSuchMethodException e) {
            L.e(this, e);
        } catch (InvocationTargetException e) {
            L.e(this, e);
        } catch (IllegalAccessException e) {
            L.e(this, e);
        }

**Comment by alexvasilkov** [comment]
Great, I will keep this ticket open until I'll find a good way to add it to public API

**Comment by alexvasilkov** [comment]
`getController().updateState()` method will always adjust zoom levels from now on, so you don't need reflection hack anymore.
