### ISSUE TITLE
Feature request: disable pinch to close

### ISSUE THREAD

**Issue by thierryd** [alexvasilkov/GestureViews#114]
Currently, if the user pinch the image below EXIT_THRESHOLD, an exit animation is automatically called. This is not the behaviour that I want in my app. :)

I suggest making EXIT_THRESHOLD a config parameter. So I could change the exitThreshold to something like 0F to disable this behaviour.

**Comment by alexvasilkov** [comment]
Do you want to disable all exit gestures or only pinch-to-exit?

**Comment by alexvasilkov** [comment]
Ah, sorry, you clearly stated it in the subject line, which rarely happens :)

Thanks for feedback, I'll check how it can better be done.

**Comment by alexvasilkov** [comment]
Added in v2.5.2.

You can enable only scroll-to-exit gesture with:
```java
image.getController().getSettings().setExitType(Settings.ExitType.SCROLL);
```
