### ISSUE TITLE
Detect image zoom state

### ISSUE THREAD

**Issue by mnnit-LaltuKumar** [alexvasilkov/GestureViews#117]
Is there any way to detect the image or video is in zoom state?. I need to hide few views on zoom state but not getting any callback from the library.

**Comment by alexvasilkov** [comment]
You can use `GesutreView.getController().addOnStateChangeListener(...)` to receive state changes and get current zoom.

If you need to find out minimum (initial) zoom level you can use `GesutreView.getController().getStateController().getMinZoom(State)`
