### ISSUE TITLE
Left and right covered

### ISSUE THREAD

**Issue by DizzyYang** [alexvasilkov/GestureViews#118]
Thanks to the author's library, I have a very long picture, use the GestureImageView control, want to be covered with high degree of self-adaptive, how should I solve?

https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1529666966489&di=87e21ab2f3e232e3f67b9d44ac1b98b8&imgtype=0&src=http%3A%2F%2Fimg.zcool.cn%2Fcommunity%2F012bc0585250e8a801219c77cf3db4.jpg

**Comment by alexvasilkov** [comment]
Sorry, didn't get it. What exactly you want to achieve?
You may play with Fit type (try fit horizontal) and gravity (try top) in settings, you may also try GestureFrameLayout.

**Comment by DizzyYang** [comment]
Thank you very much for using Fit and Gravity to solve the problem.
