### ISSUE TITLE
getSnapshot - crops in display resolution

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#12]
The `getSnapshot` function does not crop correctly. It's not cropping the underlying image but only the displayed image..

This makes this function useless for many usecases I think... Actually I don't know how to do that, any ideas on how to crop the real image? I know how to load tiles of the image, but I don't know to put them together and this would only work if I disable rotation, which would be fine for some usecases at least...

**Comment by alexvasilkov** [comment]
Yes, it is only cropping image as it is displayed to the user.

If you want to crop the correct part of the original bitmap you will need to do something like that:
1. Load bitmap into the memory (you may need to scale it down to prevent OOM error). Most likely you already have it loaded.
2. Create destination bitmap which will have size = [movement area size] / [current zoom].
3. Get current state and set zoom to 1 using pivot point in the center of the movement area.
4. Get state matrix and apply inverted matrix to the canvas tied to destination bitmap. Draw bitmap on canvas.

Note, that it is not real algorithm, it is only a starting point.
I will add this to my TODO list, but I'm not sure when I can implement it.

**Comment by MFlisar** [comment]
Can you explain how to get pivot point for the movement area? I can't find out how to get the center or any point of the movement area..

Actually it probably is enough to get `x` and `y` of the movement area in relation to the bitmap (scaled or not) + get `width` and height` of the movement area.

Getting `width` and `height` is easy:

     int scaledCropWidth = cropImageGestureView.getController().getSettings().getMovementAreaW();
     int scaledCropHeight = cropImageGestureView.getController().getSettings().getMovementAreaH();
     float scale = cropImageGestureView.getController().getState().getZoom();
     int cropWidth = (int)((float)scaledCropWidth / scale);
     int cropHeight = (int)((float)scaledCropHeight / scale);

Now I would need to know `x` and `y` of the left point of the movement area. Then I can create a bitmap directly with the data from the source bitmap

**Comment by alexvasilkov** [comment]
I decided to implement this feature myself, see 617a3774a46864e4a837baa8914dd44015e71faa.
Note, that it will take some time (maybe few weeks) to push new version, so you can either use library sources or just copypast CropUtils file for now.

**Comment by sharmadev2506** [comment]
Hi @alexvasilkov  and @alashow I am still facing this issue. Could you please help me out?
