### ISSUE TITLE
How to custom swipe distance with scale rate?

### ISSUE THREAD

**Issue by GuoJinyu** [alexvasilkov/GestureViews#121]
in small size screen,like 640*320,I swipe from centre to the edge of the screen, then image start to zoom in.but what I want is as long as I swipe with two fingers, the image zoom in immediately.

**Comment by alexvasilkov** [comment]
Sorry, I'm not sure I understand your question.
It seems like you refer to "double tap and swipe to zoom" gesture in the beginning, and you want to have a similar gesture but with 2 fingers, like "swipe with 2 fingers to zoom", is it correct?

Such gesture is not currently supported, and it does not look like a standard gesture, so I don't have plans to implement it directly in the library.

If you want to implement it yourself you can try to extend GestureController, override `onScroll(...)` method and manually check if current scroll event is performed with 2 fingers and apply your own scale logic to the state. But I don't think I can help you much with it.

BTW, can you please share your use case, why do you need to implement such a gesture?
