### ISSUE TITLE
Creating complex scrolling layouts in GestureFrameLayout

### ISSUE THREAD

**Issue by premacck** [alexvasilkov/GestureViews#122]
Can I create complex scrollable layouts in GestureFrameLayout?
I need multiple adjacent layouts with a NestedScrollView containing a 3-column grid RecyclerView in the ViewPager, that I can horizontally scroll, and dismiss on swiping down.

**Comment by alexvasilkov** [comment]
Hm, and why do you need `GestureFrameLayout` in this setup? :)

In general, there are too many nested scrollable controls, I'm not sure you can have proper scrolling logic even without `GestureFrameLayout`.

**Comment by premacck** [comment]
I guess I'll just have to build a library for that then!
