### ISSUE TITLE
Can't pan to full child view height when zoomed in

### ISSUE THREAD

**Issue by bizzyman** [alexvasilkov/GestureViews#123]
I have a layout structure as such:

```
<ConstraintLayout/>
    <ScrollView/>
        <GestureFrameLayout/>
            <ConstraintLayout/>   <-- has an image as background around 2500px
```

When I try to zoom in after moving down the scrollview (let's say to the bottom of the child element of scrollview), then when I try to pan upwards to the top of the image that is the background of my ConstraintLayout (whilst still zoomed in), I am restricted to only going upwards to a fraction of the height.

Here is an image trying to explain the issue:

![zoom](https://user-images.githubusercontent.com/17803855/44055800-5760c02e-9f3e-11e8-8290-b63e60944dfe.gif)

**Comment by bizzyman** [comment]
Sure, I have a large image as a background with text that the user needs to read (not the one in the gif), and there are several `EditText`'s along the scrollview (actually inside the bottom ConstraintLayout). 

I tried removing the Scrollview but then have 2 problems:
1) I need to be able to scroll (or pan?) the `GestureFrameLayout` programmatically, this is what I am doing with the scrollview currently
2) When I try and use an `EditText` at the bottom of the `GestureFrameLayout` the keyboard obstructs the view and there is no way to scroll down to see the `EditText`.

**Comment by alexvasilkov** [comment]
I think you can assume that GestureFrameLayout is similar to Map view. Placing map view inside ScrollView will not work well, and same for GestureFrameLayout.

You may consider to add a separate screen where user will have an option to scale and pan the layout or place it in a fixed location on the screen (e.g. on the bottom).

**Comment by bizzyman** [comment]
Is there any way to pan programmatically GestureFrameLayout?

**Comment by bizzyman** [comment]
Thank you! Sorry, one last question, is there any way to smoothly animate from one state to another? A bit like scrollView.smoothScrollTo?

**Comment by bizzyman** [comment]
Ok, I have figured it out, I create a new `State` instance and pass to `getController().animateStateTo(state)`.
Many thanks for your help, I will close this issue now!
