### ISSUE TITLE
zoom effect when swipe up or down to exit

### ISSUE THREAD

**Issue by zyyoona7** [alexvasilkov/GestureViews#124]
Can support the zoom effect when I swipe up and down to exit? Like iOS photos

**Comment by alexvasilkov** [comment]
There is no built-in option, but you can achieve it with something like this:

```Java
    public class ZoomOnExit implements ViewPositionAnimator.PositionUpdateListener {

        private static final float MIN_ZOOM_FACTOR = 0.5f;

        private final Point tmpPivot = new Point();
        private final ViewsTransitionAnimator<?> animator;

        public ZoomOnExit(ViewsTransitionAnimator<?> animator) {
            this.animator = animator;
        }

        @Override
        public void onPositionUpdate(float position, boolean isLeaving) {
            GestureImageView view = (GestureImageView) animator.getToView();

            if (view != null) {
                // Zoom-to-exit gesture will not work with this class, allowing only scroll-to-exit
                view.getController().getSettings().setExitType(Settings.ExitType.SCROLL);

                // Indirectly checking if we are in exit gesture
                float pos = view.getPositionAnimator().getPosition();
                float posTo = view.getPositionAnimator().getToPosition();
                boolean isExitGesture = pos < 1f && State.equals(pos, posTo);

                if (isExitGesture) {
                    // Calculating new zoom level
                    State state = view.getController().getState();
                    float minZoom = view.getController().getStateController().getMinZoom(state);
                    float zoom = minZoom * (MIN_ZOOM_FACTOR + pos * (1f - MIN_ZOOM_FACTOR));

                    // Calculating pivot point
                    GravityUtils.getDefaultPivot(view.getController().getSettings(), tmpPivot);

                    // Applying new zoom level
                    state.zoomTo(zoom, tmpPivot.x, tmpPivot.y);
                    view.getController().updateState();
                }
            }
        }
    }
```

And then apply it with:

```Java
animator.addPositionUpdateListener(new ZoomOnExit(animator));
```

It's mostly a hack and I can't guarantee it will work as expected though, so I would not recommend to do so.

**Comment by zyyoona7** [comment]
Thanks~ it worked for me

**Comment by alexvasilkov** [comment]
Indeed, I see a strange flashing if MIN_ZOOM_FACTOR is set to 0.5, but with 0.6 it seems to work just fine. Thanks for the observation, I will update the code above in case somebody else will want to use it.

I don't think opening ExitController is a good idea at the moment, it is an internal logic and it is not intended for external usage or modification. As long as `ZoomOnExit` example works fine with MIN_ZOOM_FACTOR = 0.6 I can't see why don't just use it instead of custom `ExitController`.

**Comment by zyyoona7** [comment]
Thank you so much, this solution is worked for me. BTW, I just want to be the same as iOS Photos, when the exit scroll gesture is triggered, I can slide left or right or in any direction with zoom out, Thanks again.

**Comment by alexvasilkov** [comment]
Swiping left/right is usually reserved for gallery browsing (e.g. ViewPager flipping), not sure it is a good idea to use it as exit gesture.

I checked Photos app in iOS simulator, swiping left/right just swipes between images, it does not have zoom animation, though I'm not an iOS user and can missing something.

Anyway, thank you for your question, I will consider adding "zoom-out on exit" animation into the library (probably with a separate setting for it)

**Comment by zyyoona7** [comment]
Sorry, Please forgive me for bad English. I hope it can follow the finger to change the position of the x axis and y axis when dragging, instead of just changing the y axis position. drag effect like [this](https://github.com/iielse/ImageWatcher).

Looking forward to your update.
