### ISSUE TITLE
Gestures are not working when scaletype is set

### ISSUE THREAD

**Issue by RanKKI** [alexvasilkov/GestureViews#128]
When I set a scale type to the view, the gestures are not working, like zoom or double click,

**Comment by alexvasilkov** [comment]
Image state is applied to image matrix, so if you'll override default "matrix" scale type with any other image matrix will not be applied and you will not see any changes. Use built-in settings to apply initial image position (`setFitMethod(...)`, `setGravity(...)`).

**Comment by RanKKI** [comment]
I see, thank you

**Comment by Saxxhw** [comment]
nnn
