### ISSUE TITLE
Return to default rotation after rotation

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#13]
How can i return view to default rotation state with animation, after rotating with fingers? Now when i rotate view with fingers it stays in rotated state.

Like in the video:
https://youtu.be/Jh-OJjtHJmQ

**Comment by alexvasilkov** [comment]
There is no out of the box support for such feature, but I will consider adding it into the library.

For now you may try next code:

        gestureView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getActionMasked() == MotionEvent.ACTION_UP) {
                    gestureView.onTouchEvent(event); // Ensure we passed event to gesture view

                    State state = gestureView.getController().getState();
                    float rotation = Math.round(state.getRotation() / 90f) * 90f;

                    if (!State.equals(rotation, state.getRotation())) {
                        State end = new State();
                        end.set(state.getX(), state.getY(), state.getZoom(), rotation);

                        gestureView.getController().getStateController().restrictStateBounds(end);
                        gestureView.getController().animateStateTo(end);
                    }
                    return true;
                } else {
                    return false;
                }
            }
        });

Note, that `restrictStateBounds(end)` is not a public method, so you have to call it with reflection.

**Comment by alashow** [comment]
Reflection didn't work before v2.1.0. Now works. Thanks :smiley:

```Java
State end = new State();
end.set(state.getX(), state.getY(), state.getZoom(), rotation);

StateController stateController = holder.image.getController().getStateController();
try {
	Method method = StateController.class.getMethod("restrictStateBounds", State.class);
	method.invoke(stateController, end);
} catch (Exception e) {
	e.printStackTrace();
}
```

**Comment by alexvasilkov** [comment]
Hm, strange, this method was there almost from the beginning.
BTW, now you should not need to call `restrictStateBounds(end)` with reflection, state restrictions should be applied automatically inside `animateStateTo(end)`.

**Comment by alashow** [comment]
My bad. I didn't see logs, NoSuchMethodException were throwing. Yeah, it works now because you updated ```animateStateTo(end)```, i think.

**Comment by alexvasilkov** [comment]
In new version 2.1.1 I added `setRestrictRotation` option in `Settings` which should do exactly what you want. Please check if works fine for you.

**Comment by alashow** [comment]
Yes, thanks a lot!

btw, when are you planning to make "Allow scroll up/down gestures to close full image mode.", from TODO?

**Comment by alexvasilkov** [comment]
I'm not sure, I think it may take several months. It is an interesting feature, but it's hard to find a nice solution and I don't have enough time right now.

**Comment by alashow** [comment]
@alexvasilkov https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/ui/PhotoViewer.java telegram-s photoviewer is awesome. maybe you will find some solution from it. His code hard to understand, but it works.

**Comment by alexvasilkov** [comment]
Yeah, I looked it a bit, but it is a complete mess. Anyway I have different implementation which requires different logic.
