### ISSUE TITLE
packagerelease not found

### ISSUE THREAD

**Issue by ShimmerSummer** [alexvasilkov/GestureViews#134]
Task with name 'packageRelease' not found in project ':sample'.

**Comment by ShimmerSummer** [comment]
how to use it?
i only add the dependendy, is it okay?

**Comment by alexvasilkov** [comment]
If you want to use the library then just include it as stated in README. If you want to build the sample app you should use Android Studio or run `./gradlew :sample:assembleDebug` and then install the resulting apk file.
