### ISSUE TITLE
Please add code from viewpager to viewpager?

### ISSUE THREAD

**Issue by dhavalappspool** [alexvasilkov/GestureViews#135]
#133

**Comment by dhavalappspool** [comment]
And please add code of full screen image remove functionality

**Comment by alexvasilkov** [comment]
Sorry, I'll close this issue as it is pretty confusing:

* You didn't provide use case for ViewPager to ViewPager image animation, and I cannot think of a good use case myself.
* You linked unrelated pull request.
* I don't understand what kind of "remove" functionallity you meant for "full screen image".
