### ISSUE TITLE
GestureFrameLayout in ViewPager which is one item of RecyclerView with PagerSnapHelper

### ISSUE THREAD

**Issue by shuifengYu** [alexvasilkov/GestureViews#137]
I have a RecyclerView attached to PagerSnapHelper, and each item of the list is an array of images, so i use a ViewPager to show the images, it means the item of the RecyclerView is ViewPager, and each item of the ViewPager is a GestureFrameLayout contains a ImageView which extends SimpleDraweeView in it, so is it possible to response the dragging event of RecyclerView to move to previous or next item ？Thanks！

**Comment by alexvasilkov** [comment]
You have a very complicated setup so I really not sure how to help you. If you can provide a sample project that shows this issue then I could probably help to check what is not working there.

(Late response, so I just close the issue for now)
