### ISSUE TITLE
Image Crop Loading...

### ISSUE THREAD

**Issue by NisheshJain** [alexvasilkov/GestureViews#138]
How to show Loader/Progress when image in Cropping and store in Local storage.

**Comment by alexvasilkov** [comment]
This library does not provide any logic to store cropped image on disk. You'll receive cropped image as bitmap immediately and it is up to you to implement any disk storage operations (should run in background thread) and show progress while you are saving the bitmap.

You can check this SO question to find out how to store bitmap into a file: https://stackoverflow.com/questions/649154/save-bitmap-to-location
