### ISSUE TITLE
GestureFrameLayout with  a child ScrollView dose not work

### ISSUE THREAD

**Issue by iloveaman** [alexvasilkov/GestureViews#14]
GestureFrameLayout with  a child ScrollView dose not work

**Comment by alexvasilkov** [comment]
This layout is not compatible with ScrollView. But you can use next settings to achieve similar behavior:

    layout.getController().getSettings().setFitMethod(Fit.HORIZONTAL).setGravity(Gravity.TOP);

I also fixed GestureFrameLayout to properly work with wrap_content dimension of child view, it will be available in next release.
