### ISSUE TITLE
Sometimes getViewHolder is empty

### ISSUE THREAD

**Issue by tcqq** [alexvasilkov/GestureViews#142]
@alexvasilkov If delete the arrow code, an exception occurs when you click on the item and open the image.
![image](https://user-images.githubusercontent.com/10644057/59156347-1746fb00-8acc-11e9-832a-14cb851e9ff5.png)

Because sometimes `getViewHolder` is empty, so should change the value of getViewHolder to `@Nullable`.
![image](https://user-images.githubusercontent.com/10644057/59156321-c8996100-8acb-11e9-8dfe-21c3ab680d04.png)

**Comment by alexvasilkov** [comment]
Didn't get the problem here. Just don't remove the mentioned code and use nullable type in Kotlin.
