### ISSUE TITLE
Can I revert to the original size of the image view when I release my hand?

### ISSUE THREAD

**Issue by sinwho** [alexvasilkov/GestureViews#143]
Can I get back to normal when I turn my finger on the screen during multi-zoom?

**Comment by mahditakrim** [comment]
Hi @sinwho ,
Could you please explain the issue a little bit more and address the class or directory of cause (where you handle touch events of the screen) so I can work on it ?

**Comment by alexvasilkov** [comment]
Hi, sorry for late response.
I beleive that you can achive the desired behavior (returning the image to initial state after zoom gesrture) using the next settings:

```
settings.setMaxZoom(0.01f);
settings.setOverzoomFactor(10f);
```
Or in xml:
```
app:gest_maxZoom="0.01"
app:gest_overzoomFactor="10"
```

Basically you are asking the image to not zoom beyond min zoom level. And big "overzoom" factor makes it easier to zoom-in the image with pintch gesture.
