### ISSUE TITLE
Support for Viewpager2

### ISSUE THREAD

**Issue by SaikrishnaRajaraman** [alexvasilkov/GestureViews#144]
ViewPager2 is based on RecyclerView adapters. Please give support for ViewPager2.

**Comment by ajkiosd** [comment]
I really need ViewPager2 support.
I try to implement it by changing ViewPager to ViewPager2 in the library but it didn't work.
Any Help?

**Comment by alexvasilkov** [comment]
The ViewPager2 support is part of v2.8.0. Finally :)
