### ISSUE TITLE
Hi, and thanks for the great library. I want to ask if I can disable the one finger movement on the zoomed layout and keeping two fingers move??

### ISSUE THREAD

**Issue by SaadMusallam** [alexvasilkov/GestureViews#145]

**Comment by alexvasilkov** [comment]
Hi @SaadMusallam, sorry for late reply. I see that you closed the task. Did you manage to do this yourself?

**Comment by SaadMusallam** [comment]
yes I managed it myself, thanks a lot.

**Comment by alexvasilkov** [comment]
Can you maybe share a few tips how this can be done? In case somebody else will need it too.
