### ISSUE TITLE
How to listen to missing gesture listeners?

### ISSUE THREAD

**Issue by ParticleCore** [alexvasilkov/GestureViews#146]
I'm trying to listen to common gestures such as `onFling` and `onScroll`, but these aren't available in the `GestureController.OnGestureListener`, isn't there a way to listen to these through the GestureView library?

**Comment by alexvasilkov** [comment]
You can listent for basic events using `GestureController.setOnGesturesListener()`.
It does not allow you to handle scroll and fling gestures though since they are consumed by the library and transformed to image state changes.

Please describe your use-case, why do you need those callbacks?

**Comment by ZhuSky** [comment]
@alexvasilkov I have the same problem.
I need to monitor scrolling events,
For handling external drawer effects.
Is there a listeners like this???

**Comment by alexvasilkov** [comment]
@ZhuSky Android's drawer does not require setting scroll listener to child views, instead it is implemented as a view group that intercepts touch gestures from its children.
