### ISSUE TITLE
Recyclerview in the GestureFrameLayout is not scrolling. 

### ISSUE THREAD

**Issue by malikthebest** [alexvasilkov/GestureViews#148]
Recyclerview in the GestureFrameLayout is not scrolling. I'm trying to integrate it with the gestures enabled to finish activity with the dragging. It drags the layout first instead of recyclerview.

**Comment by alexvasilkov** [comment]
I addressed this issue in de0f9b091670c24b169144235f6fcb507c90d6db, which is releases in v2.6.0 now. Please try the last version and re-open this issue if it still won't work for you.
