### ISSUE TITLE
are there any sample code about cross activities from recyclerview to viewpager?

### ISSUE THREAD

**Issue by malikthebest** [alexvasilkov/GestureViews#149]
Is there any sample code about cross activities from recyclerview to viewpager? I'm looking to animate from one activity to another but unable to understand how to use animations

**Comment by alexvasilkov** [comment]
Sorry, there is no such example. Cross-activity animation is quite tricky, and when applied to "list to page" animation it becomes even more complicated, it will require to create a constant communication channel between two activities. I'm not planning to provide such an example in forseable future.

You can try to do it yourself by looking into provided examples for cross activity animation and for "list to pager" animation.
