### ISSUE TITLE
It will be grateful if you could guide when users want to handle their own images, but not Flickr images.

### ISSUE THREAD

**Issue by wann2** [alexvasilkov/GestureViews#150]
This library is excellent, I'd like to use it.
but it is difficult to implement with my own images, but not Flickr images.
It will be grateful if you could guide when users want to handle their own images.

**Comment by alexvasilkov** [comment]
You can use any image loading libraries out there (Glide, Picasso, etc). The library does not handle the loading in any way and Flickr is only used as a demo.
