### ISSUE TITLE
 How to improve the drawing efficiency of this View？

### ISSUE THREAD

**Issue by MonstersXu** [alexvasilkov/GestureViews#152]
I have turned on hardware acceleration through setLayerType(LAYER_TYPE_HARDWARE, null), but the animation effect is still very stuck on some phones..

**Comment by alexvasilkov** [comment]
I'll close this issue as it is too vague. You don't provide any info except that it is "very stuck on some phones".

Note that you don't need to set hardware acceleration unless you excplicitly disabled it yourself. If your activity has a mix of software and hardware accelerated views then it can be a problem as well.
