### ISSUE TITLE
how to trigger doubleTap in code

### ISSUE THREAD

**Issue by hegelsu** [alexvasilkov/GestureViews#157]
1. how to get current scale value in code?
2. how to trigger doubleTap in code?
3. how to disable animation?

**Comment by ZhuSky** [comment]
@hegelsu I found it possible to get through 
`State state = controller.getState()`
1. state.getZoom()

**Comment by alexvasilkov** [comment]
1. `getController().getState().getXxx()`
2. `getController().animateStateTo(getController().getStateController().toggleMinMaxZoom(state, x, y))`
3. Not sure what you mean by disabling animations. You can disable gestures with `getController().getSettings().disableGestures()`.
