### ISSUE TITLE
Firing the onDown Gesture Listener even on one tap

### ISSUE THREAD

**Issue by heyou93** [alexvasilkov/GestureViews#16]
Hi,

The onDown Gesture Listener  event is executing even on one tap. As well as the upOrCancel. I am loading my image on a new activity and i want to close the activity upon draging the image up or down just like in twitter.

here is my code:

```
mImage.getController().setOnGesturesListener(new GestureController.OnGestureListener() {
            @Override
            public void onDown(MotionEvent e) {
                finish();
            }

            @Override
            public void onUpOrCancel(MotionEvent e) {
        
            }

            @Override
            public boolean onSingleTapUp(MotionEvent e) {
                return false;
            }

            @Override
            public boolean onSingleTapConfirmed(MotionEvent e) {
                return false;
            }

            @Override
            public void onLongPress(MotionEvent e) {

            }

            @Override
            public boolean onDoubleTap(MotionEvent e) {
                return false;
            }
        });

```

**Comment by alexvasilkov** [comment]
Methods `onDown` and `onUpOrCancel` are called when corresponding `MotionEvent` is detected. They are not a "drag down" / "drag up" callbacks.

The feature you are talking about is not currently supported, but it is in my [TODO list](https://github.com/alexvasilkov/GestureViews/wiki/TODO).
