### ISSUE TITLE
Fully zoomed out

### ISSUE THREAD

**Issue by HyperionElectronicsCo** [alexvasilkov/GestureViews#161]
Once fully zoomed out I wish it not to go further,

What controls would I have to set to stop it from zooming in to negative, I know it springs back after but I wish to stop this entirely

If 100%, pinch inwards = null

**Comment by alexvasilkov** [comment]
You can use `setOverzoomFactor(1f)`, see [usage wiki](https://github.com/alexvasilkov/GestureViews/wiki/Usage).

**Comment by HyperionElectronicsCo** [comment]
Just crashes when adding the setting unfortunately

**Comment by alexvasilkov** [comment]
Should not "just crash" if you set it to 1f, but I cannot help if you don't provide stacktrace and other details about your issue.

**Comment by HyperionElectronicsCo** [comment]
I'm using AIDE to compile all my code on 9/10 times it doesn't produce a Logcat

I tried declaring it, then find viewbyid 

Then the setting in wiki and it just crashed, I can't give anymore info, I can however send you my code if you have an email and then you could maybe tell me where I'm going wrong 

I'm using your code as part of my IDE
![Screenshot_20200909_230404_com hyperion nextide](https://user-images.githubusercontent.com/67075760/92659748-e5d16680-f2f0-11ea-8215-4035f6d67d68.jpg)

**Comment by alexvasilkov** [comment]
Ability to debug and get logs is essential in development, you have to find a way to get crash logs. If you write your app in Java and it crashes then there must be a stack trace in the logs.

You can share corresponding part of your code here on GitHub, but without logs it may be hard to spot an issue.

**Comment by HyperionElectronicsCo** [comment]
I'll try and get a log
