### ISSUE TITLE
Demo app not accounting for insets

### ISSUE THREAD

**Issue by ParticleCore** [alexvasilkov/GestureViews#163]
A minor issue, but might want that looked at. I was trying the demo app today and I noticed the bottom section of the view pager is not accounting for the navigation inset to offset the information vertically, otherwise it gets overlapped.

![image](https://user-images.githubusercontent.com/9222661/99098990-caf8c800-25a7-11eb-8aac-9db2b82ff58d.png)

**Comment by alexvasilkov** [comment]
Fixed in v2.7.0
