### ISSUE TITLE
Question about Advanced Demo

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#17]
Hi, 

Thank you for a great library. I really love it! I just have one question about the advanced demo.

If I use a fixed size grid view (2x2) instead of recycler view, will everything work fine? 

Best,
Martin

**Comment by alexvasilkov** [comment]
Hi, glad you like it!

If you meant `GridView` then there is no support for it now, so I suggest you to switch to `RecyclerView` instead.

For regular layouts you can try something like this:

    animator = new ViewsTransitionBuilder<T>()
                .intoViewPager(pager, pagerTracker)
                .build();
    animator.setFromListener(new ViewsCoordinator.OnRequestViewListener<T>() {
                    @Override
                    public void onRequestView(@NonNull T item) {
                        View view = findViewByItem(item);
                        animator.setFromView(item, view);
                    }
                });

So you only need to implement `findViewByItem` method.

**Comment by sangwoo419** [comment]
Hi, thank you so much for the support!

I tried the above method, but it seems like it is not working as I expected.

I am trying to implement something like this through advanced demo:

![example](https://cloud.githubusercontent.com/assets/16851575/12702004/4749e44a-c85e-11e5-966f-effe48ae897c.png)

Best,
Martin

**Comment by alashow** [comment]
I think you just need to create something like `IntoRecyclerViewListener.java`
