### ISSUE TITLE
EditText not editable in GestureFrameLayout

### ISSUE THREAD

**Issue by Equin** [alexvasilkov/GestureViews#171]
Hello, i have complex view. its like a book with images and text. build with GestureFrameLayout and ViewPager in it. I am using GestureFrameLayout  to have posibility zoom in/out to/from elements. With images it works ok. but when zooming to EditText keyboard not showing and EditText not changing its value when typing. if i remove zooming keyboard shows and EditText works like expected. Can you help me please ? Thanks!

**Comment by Equin** [comment]
Any help on this ?

**Comment by alexvasilkov** [comment]
Edit text seems to work fine, at least when I add it to sample app and test on Samsung S10. I may need more details to understand what is going on.
Keyboard may cover the edit text though if it's zoomed in / scrolled, maybe there are some other issues with edit text focusing, I never tested this scenario tbh.
