### ISSUE TITLE
Two questions about GestureViews library.

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#18]
Hi, thank you so much for the support!

1. 
I tried the method you suggested, but it seems like it is not working as I expected. I am trying to implement something like this through advanced demo:
![untitled-1](https://cloud.githubusercontent.com/assets/16851575/12708444/d6f3eda0-c8e2-11e5-94b9-9822a54d418e.png)

Would this be possible? Actually using shard element would be the best solution. Yet, shared element is only supported in Android Lollipop. In addition, I really love the integration of gesture controls like pinch zoom, rotation and etc.

2.
I would like to implement Onclicklistener to GestureImageView. Yet, it seems like the Onclicklistener is not functioning when I disable gestures. How can I implement Onclicklistener while calling disableGestures() method.

Best,
Martin

**Comment by alexvasilkov** [comment]
1. I'm not sure how this transition should look like, dark blue element should move to it's new position, while 3 others should fade in? You may try to write your own "into" listener (similar to suggestion from #17), in case of fixed 2x2 RecyclerView it should be straightforward. Alternatively you may try to animate it yourself, though it may require quite a lot of maths.

2. Try to disable all gestures except panning. If you'll disable all gestures using `disableGestures` no gestures will be detected.

**Comment by sangwoo419** [comment]
Hi, thank you for the support!

I have another question about gestureviews and advanced demo. Is it possible to use the pinch gesture (zoom out) to go back to the recyclerview (3xinfinite) from viewpager? For example, if users pinch out from photos, it will go back to the tiled thumbnail mode. 

Thanks!

**Comment by alexvasilkov** [comment]
Not now, but it's in my [TODO list](https://github.com/alexvasilkov/GestureViews/wiki/TODO).

**Comment by sangwoo419** [comment]
Hi. I have another question. how can i use Center_Crop option? thanks.

**Comment by alexvasilkov** [comment]
This widget is not intended to crop image in any way. But you can achieve similar behaviour using `setFitMethod(Fit.OUTSIDE)` and disabling all gestures.

**Comment by sangwoo419** [comment]
Thanks! I really appreciate your help. 

My main problem is that I would like to use OnClickListener with GestureImageView that has a Center_Crop option.

I want to make a clickable center-cropped ImageView that does not have any gesture. That is, I actually just want to use the advanced demo animation, which is similar to the sharedElement animation. Since Android Kitkat does not provide sharedElement feature, I was planning on using this library to mimic the shared element animation on Kitkat running devices. (to give Kitkat users the same experience as Lollipop/Marshmallow users) Could you please tell me if this is possible through this library? If possible, would making a custom view with AnimatorView interface solve this problem?

Again, thank you so much for a great library.

**Comment by alexvasilkov** [comment]
1. **Click listener**. I see 2 options:
a. Crop images before setting them into image view (Glide can do it for you)
b. Add overlay view and handle it's clicks.

2. **Shared element**. I haven't had in mind to use this library as replacement for shared element animation, so I doubt you can use it for it.
You may try to implement it yourself. Start with `ViewsCoordinator` class, once you have positions of 2 views you may animate from one bounds to another using standard animation API.
