### ISSUE TITLE
Unable to implement the rotation

### ISSUE THREAD

**Issue by JamoDavid** [alexvasilkov/GestureViews#2]
Hi, I'm using GestureImageView on a project, the issue here is that i'm uncapable to implement the rotation, actually i haven't find the way to do it. the only thing i can do for now is the zoom capabilty. If you could please tell me how to do the rotation and crop  I'll be very grateful. 

Also, what is the difference between GestureImageView and GestureImageViewFull?

**Comment by alexvasilkov** [comment]
Hi,

It looks like you use old version of the library, please try latest 2.0.0-beta-2. But note, that library is still in development, so there may be some breaking changes until I'll move it out of beta.

As of rotation, it should be possible to enable it with Settings.setRotationEnabled(true), see corresponding [example activity](https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/activities/ImageCropActivity.java). Do you have troubles with it?

There is no GestureImageViewFull class anymore, it was intended to animate images from i.e. list item to full screen (as can be seen in Flickr sample), but lately I chose another way to do it.

**Comment by JamoDavid** [comment]
Thanks for the complete answer Alex, it was  actually very helpful. I'm closing this issue but not before I tell you that this library is by far the best library for image controlling i have encountered. Keep the great work and thank you!

**Comment by alexvasilkov** [comment]
Thanks, really nice to hear
