### ISSUE TITLE
Advanced Demo Sync Issue

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#21]
Hi,

**Previous Problem:** I have problem where if list gets updated on ViewPager mode, the ViewPager automatically exits and the RecyclerView gets updated.

**Update:** I found that when I swipe ViewPager quickly the ViewPager shuts by itself and the list is updated on the RecyclerView. However, if I swipe the ViewPager slowly the ViewPager works perfectly. (not shutting by itself)

We have a very similar environment as the Advanced Demo. One difference is that we have complex ViewPager PageTransformer (thus, it is the drawing process is a bit heavier). Do you have any idea why this might happen? 

Thank you so much!

**Comment by sangwoo419** [comment]
We solved the problem by overriding the exit method. Thanks!

**Comment by alexvasilkov** [comment]
Great, could you please share your solution, in case somebody will face same problem?
