### ISSUE TITLE
Quick scale zoom bug

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#22]
I was playing with quick scale (double tap then slide) zoom and i found weird bug: when i move my fingers fastly, imageview rotates 180°.

Here is the video: https://drive.google.com/file/d/0B5up2CgQawSDanRTM0VFZHNDQms/view

**Comment by alexvasilkov** [comment]
It's finally fixed, will be available in upcoming release.

**Comment by alashow** [comment]
Glad to see progress in this awesome project!

**Comment by alexvasilkov** [comment]
Thanks, still not so much time, but I hope to implement few more features soon :)
