### ISSUE TITLE
question about advanced demo animation duration

### ISSUE THREAD

**Issue by sangwoo419** [alexvasilkov/GestureViews#23]
Hi,

Is it possible to change the duration for the advanced demo animation (the shared element-like animation)? I want the picture to move to the center quicker. 

Thank you!

**Comment by alashow** [comment]
In documentation it says to use "setDuration" from `ViewPositionAnimator` but first I also couldn't find access to positionAnimator from `mAnimator` (`ViewsTransitionAnimator<Integer>`).

But looks like you can (or the only way) set duration from `photoPagerAdapter` (`FlickrPhotoPagerAdapter.java`) when configuring `gestureView` settings ([here](https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/adapters/FlickrPhotoPagerAdapter.java#L77)) like this:
```java
holder.image.getPositionAnimator().setDuration(1000);
```

**Comment by sangwoo419** [comment]
Thank you so much that worked!
