### ISSUE TITLE
The division into sections

### ISSUE THREAD

**Issue by IamEgor** [alexvasilkov/GestureViews#27]
Hello. Thanks for your library.
I'm trying to do Recyclerview with several viewholders. First is parent and second is child.
![device-2016-03-17-210900](https://cloud.githubusercontent.com/assets/7051238/13856077/9a47a138-ec84-11e5-90ae-8b6a95c15233.png)
![device-2016-03-17-210831](https://cloud.githubusercontent.com/assets/7051238/13856078/9a481a5a-ec84-11e5-8989-31f59a2528a1.png)
I want Viewpager to scroll only sub pictures from it's subcategory. 
What is the better way to achieve this?

I tried to pass sublist of photos, but then I couldn't find the way to scroll recyclerview to position on exit.

**Comment by alexvasilkov** [comment]
It seems you should implement custom [ViewsTracker](https://github.com/alexvasilkov/GestureViews/blob/master/library/src/main/java/com/alexvasilkov/gestures/transition/ViewsTracker.java) instead of SimpleViewsTracker when creating transition animator. Here you should provide items-to-ids mapping for both `RecyclerView` and `ViewPager`.

**Comment by IamEgor** [comment]
I really stuck with this. I've got data and I split it like this. 
![image](https://cloud.githubusercontent.com/assets/7051238/13875352/6156296e-ed0e-11e5-9292-1d732681d232.png)
I can get new and old indexes. But I can't assemble it together.
Please, help me with this problem.

**Comment by alexvasilkov** [comment]
So you have both IDs (H1, a, b, c, ...) and positions in both `RecyclerView` and `ViewPager`, so you just need to implement `ViewsTracker` for `RecyclerView` (should map i.e. x <-> 6, y <-> 7 and so on) and for `ViewPager` (should map x <-> 0, y <-> 1and so on). What difficulties do you have?

**Comment by IamEgor** [comment]
Hello again.
I've implemented custom ViewTracker as you said and it works nearly perfect. 
There is only one problem : when I'm scrolling in ViewPager and the element following the last of my group is not placed out of the screen, I'm getting class cast exception. And it's absolutely right, because this next element should be a header.
I'll explain it with the pucture :
That's OK, because header is visible.
![device-2016-03-24-014601](https://cloud.githubusercontent.com/assets/7051238/14003325/cb379ce8-f162-11e5-83a9-5f61b8b29bbe.png)
That's NOT OK. Header is invisible.
![device-2016-03-24-015004](https://cloud.githubusercontent.com/assets/7051238/14003326/cb39310c-f162-11e5-82f1-4b3255a48f83.png)
I think problem is in this place : 
https://github.com/alexvasilkov/GestureViews/blob/4c628325577e64689bf0c2e5c6c01dd03529bd6e/library/src/main/java/com/alexvasilkov/gestures/transition/internal/IntoViewPagerListener.java#L71-L72
For example when I scroll to 8'th element in my ViewPager it tries  to silently scroll  to 9'th position (it invokes getIdForPosition(9)  when ViewPager is on  8 position) . But 9'th has different type, so class cast exception is inevitable.
Is there any way to solve this problem?

**Comment by IamEgor** [comment]
My bad. Everything works fine.
