### ISSUE TITLE
Animation - RecyclerView to RecyvlerView

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#28]
I want to have a hierarchie (like folders), so clicking an item in the `RecyclerView` will open another `RecyclerView` (instead of a `ViewPager`).

Is it somehow possible to adopt your animator to support a `RecyclerView` as detail view?

**Comment by alashow** [comment]
See #18

**Comment by alexvasilkov** [comment]
Nope, this requires tracking multiple items in both lists and a bit different kind of animation. It is out of scope of this library, sorry.
