### ISSUE TITLE
Resizeable scrollable view

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#30]
I saw that all your examples work with handing on the gestures to the controller and the parent is disabled or ignored.

I would like to change the columns of a `RecyclerViews` `LayoutManager` with a gesture...

Actually, I would need the controller to only consume the pinch gesture and to hand on all other gestures to the parent (clicks, scroll events). How would I do that?

**Comment by alexvasilkov** [comment]
I think this library will not help you here. You should manually handle pinch zoom with `android.view.ScaleGestureDetector`.
