### ISSUE TITLE
Animating from Rounded (Circle) ImageViews feature

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#32]
Hi, I would like to animate from rounded corners image view (I use https://github.com/hdodenhof/CircleImageView). Is it possible to add feature changing imageView round level while animating imageView?

Currently it works like this (I made circle imageView post images just for test): https://www.youtube.com/watch?v=Ekv4rY5H3co

**Comment by alexvasilkov** [comment]
Interesting feature, thank you.
And it was pretty easy to implement (check [this video](http://sendvid.com/eu9k9jy1)). First I though it will be slow, but I didn't notice any performance issues.
You can find my implementation in [this gist](https://gist.github.com/alexvasilkov/3ca1f9625cff5ea9ef0278fe32c9b3c1).
Note, that if you use Glide you should better use `asBitmap()` feature, in this case you will not have overhead of creation additional bitmap from GlideDrawable.

**Comment by alashow** [comment]
Thanks for quick response!

Works perfectly!
