### ISSUE TITLE
Updating another view with an animation WHILE scaling image

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#34]
I want to show the zoom level as an overlay. The problem is, that zooming seems to block the UI thread and so following does only start, when I stop zooming. The bahaviour is following:

_start zooming and don't stop zooming => function below will be called multiple times but the view with the zoom info won't be displayed. Stop zooming and then the zoom will be shown._

Any ideas how to solve that?

    public void updateZoomDisplay(Float zoom)
    {
        if (tvPagerTempInfo == null)
            return;

        if (zoom == null)
            tvPagerTempInfo.setText("");
        else
            tvPagerTempInfo.setText(String.format("%.2f%%", zoom * 100f));

        tvPagerTempInfo.getHandler().removeCallbacksAndMessages(null);
        tvPagerTempInfo.animate().cancel();
        tvPagerTempInfo.animate().alpha(1f).setDuration(500).start();
        // following line always works!!!!
        // tvPagerTempInfo.setAlpha(1f);
        tvPagerTempInfo.postDelayed(new Runnable()
        {
            @Override
            public void run()
            {
                tvPagerTempInfo.animate().alpha(0f).setDuration(500).start();
            }
        }, 1500);
    }

**Comment by alexvasilkov** [comment]
I can't see how it is connected to the library. All animation is performed on UI thread and should not block anything. Please use StackOverflow for questions like this.
