### ISSUE TITLE
Open image animation won't work if source image is not visible

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#35]
I'm talking about the opening animation from `RecyclerView` to `ViewPager`. Normally you click on an image to open it, so there's no problem, because the source view in the `RecyclerView` is drawn and visible.

I have a use case, where I allow to select items and then click open in the menu, so in this scenario the first image won't always be visible. I have to scroll to the correct postion before calling `animator.enter` to get it working...

As you control the scrolling in the `RecyclerView` in your library already if the `ViewPager` is shown (to keep both views in sync), could you add this as well?

Here's is what I do now to get this working:

	Runnable openRunnable = () ->
	{
        // init and prepare everything and start enter animation
	};
	
	int firstPos = ...; // get first pos of RecyclerView, the source view that will be animated
	boolean viewIsVisible = RecyclerViewUtil.isViewVisible(mMediaHelper.rvContent2, firstPos);
	// first scroll, then open the image if scrolling is finished
	if (!viewIsVisible)
	{
		recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener()
		{
			@Override
			public void onScrollStateChanged(RecyclerView recyclerView, int newState)
			{
				super.onScrollStateChanged(recyclerView, newState);
			}

			@Override
			public void onScrolled(RecyclerView recyclerView, int dx, int dy)
			{
				super.onScrolled(recyclerView, dx, dy);
                                recyclerView.removeOnScrollListener(this);
			        runnableInner.run();
			}
		});
		recyclerView.scrollToPosition(realPos);
	}
	// open the image, source image is visible
	else
	{
		openRunnable.run();
	}
	
Here's my RecyclerViewUtil helper function:

    public static boolean isViewVisible(RecyclerView rv, int index)
    {
        int firstVisible = findFirstVisibleItemPosition(rv);
        int lastVisible = findLastVisibleItemPosition(rv);
        return firstVisible <= index && lastVisible >= index;
    }
	
	public static Integer findFirstVisibleItemPosition(RecyclerView rv)
    {
        if (rv.getLayoutManager() instanceof LinearLayoutManager)
            return ((LinearLayoutManager)rv.getLayoutManager()).findFirstVisibleItemPosition();
        else if (rv.getLayoutManager() instanceof GridLayoutManager)
            return ((GridLayoutManager)rv.getLayoutManager()).findFirstVisibleItemPosition();
        return null;
    }

    public static Integer findLastVisibleItemPosition(RecyclerView rv)
    {
        if (rv.getLayoutManager() instanceof LinearLayoutManager)
            return ((LinearLayoutManager)rv.getLayoutManager()).findLastVisibleItemPosition();
        else if (rv.getLayoutManager() instanceof GridLayoutManager)
            return ((GridLayoutManager)rv.getLayoutManager()).findLastVisibleItemPosition();
        return null;
    }

**Comment by alexvasilkov** [comment]
I'm not sure about use case for such a feature, it seems rare and there is no big problem implementing it from outside the library.

Probably you can simplify your code by always calling `recyclerView.scrollToPosition(realPos);` and then listen for first "OnGlobalLayout" event from RecyclerView's tree view observer to run enter animation. But I never tested it myself, so it may not work as I think.
