### ISSUE TITLE
How to get minimal zoom factor

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#37]
I want to find out what the current minimal zoom level if the `GestureView` is (respecting the current setup).

So that I can check if the user has manually zoomed in already or not and that I can check if the user has fully zoomed out

**Comment by alexvasilkov** [comment]
Min zoom is computed dynamically, so it is a bit borrowed down in code. You can get it by `getController().getStateController().getEffectiveMinZoom()`

**Comment by MFlisar** [comment]
Thanks. Just could not find that

**Comment by MFlisar** [comment]
Can you you please help with following as well:

I want to get the current visible region of the bitmap. I want to know, if the user has panned to the left or right edge of the image. i think i have to calculate this myself with the help of the matrix I can get via the state of the GIV. Is there a simplier way already available?

Thanks
