### ISSUE TITLE
Images don't show up for w>>h types

### ISSUE THREAD

**Issue by stripathi669** [alexvasilkov/GestureViews#38]
Hi

I am using `GestureImageView` and I have noticed that the image won't show up if the image is panoramic i.e. w>>h.

Settings used on controller:

```
   img.getController().getSettings()
           .setFillViewport(true)
            .setFitMethod(Settings.Fit.HORIZONTAL)
            .setGravity(Gravity.CENTER);
```

All other settings are default. I have tested the same image on normal image view, and it shows up.

**Comment by alexvasilkov** [comment]
Tested with image 16000 x 2700, works fine. Most probably image is not loaded because of out of memory error.
Anyway, it is not a problem of the library, since it works with whatever images are set to it and does not load images itself.
