### ISSUE TITLE
BitmapRegionDecoder support

### ISSUE THREAD

**Issue by kyze8439690** [alexvasilkov/GestureViews#4]
This is the best image gallery library I have seen, thank you so much for your amazing work.
I would like to make a suggestion, is that possible to add BitmapRegionDecoder support? I see these is a ViewClipHelper class which is used for draw part of view, and GestureViews support Matrix, so I think it is possible to add BitmapRegionDecoder support, which will make ImageView support huge image zoom in/out without OOM.

**Comment by alexvasilkov** [comment]
Yeah, thanks for suggestion. I thought about region decoder feature, but I decided that main goal of this library is to provide animation mechanism and gestures control, while images decoding should be done externally. I think this can be done by using state listener and animation start / stop listener (which is missing right now, but I can add it if someone decides to implement such feature).

Unfortunately I have no plans to do it myself, so if you need this feature consider using [Subsampling Scale Image View](https://github.com/davemorrissey/subsampling-scale-image-view).
