### ISSUE TITLE
Supporting arbitrary large images with good zoom

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#40]
What is the way to go, if I want to display images that are too large for a device, which will result in `Bitmap too large to be uploaded into a texture` exception?

Normally, this would be solved by subsampling... With your view, it seems like i have to scale the image I want to display before loading it, but then zooming will loose quality...

I'm not sure how to implement subsampling with your library. It seems, like your zoom view is not meant for that... Any help or guide for that?

**Comment by alashow** [comment]
see #4

**Comment by MFlisar** [comment]
I would prefer to use this view... And implement region decoding myself...  @alexvasilkov  is mentioning that he would add the listeners for such a feature... I would really like to have them, then I would make this feature myself...

I already tried using the `Subsampling` view and I saw, that some phones are having quite some performance problems with it... That's why I want to try another apporach...

**Comment by alexvasilkov** [comment]
I added `OnStateSourceChangeListener` listener, which will be called whenever state's source is changed (whether image is controlled by user, by animation or idle). So having this listener you can run region decoder once image becomes idle. Visible region can be computed using state and settings objects. It may be a bit tricky when image is rotated, but for non-rotated image it should be pretty straightforward.
Let me know if you'll decide to implement subsampling feature yourself :)

**Comment by tibbi** [comment]
Im trying to mix GestureViews and SubsamplingScaleImageView, but not sure which way should I take. Can GestureImageView stay an ImageView, or it has to be changed to a View as in Subsampling with tiles? Not sure how could I update a part of an imageview.
