### ISSUE TITLE
Not able to load image from my own image url

### ISSUE THREAD

**Issue by ShreyashPromact** [alexvasilkov/GestureViews#43]
Hello,

I want to use this library for my own project. But the issue is this library support for flicker photo object. I want to load my own URL which is not working here with this library.

Please let me know if it is possible to do with this library.

Sincerely,
Shreyash

**Comment by alexvasilkov** [comment]
Flickr is used only for demo purposes in sample project. Library itself does not restrict source of images anyhow.

**Comment by ShreyashPromact** [comment]
@alexvasilkov 

Thanks for the reply. Please let me know if you provide the update which support own URL of Images.

Thanks.
Shreyash,
Shreyash

**Comment by alexvasilkov** [comment]
It will not happen. You can load images using plenty of 3rd party libs like Glide, Picasso, UIL and so on.

**Comment by ShreyashPromact** [comment]
@alexvasilkov 
I have try a lot but I am not able to load my own Image URL in this project.

Sincerely,
Shreyash

**Comment by alashow** [comment]
Like Alex said, the project has nothing to do with image loading.

See @bumptech/glide (as it's used in demo app) and @square/picasso for troubleshooting image loading (your "own Image URL").

Glide Usage (From Glide README):
```Glide.with(this).load("http://goo.gl/gEgYUd").into(imageView);```

**Comment by ShreyashPromact** [comment]
@alashow @alexvasilkov 

As I have said in my issue, I want to use My own Image URL to load that image in this project, which is not getting happen. So I have raised it like, it is the only work with local image and not with the Image URL.

Sincerely,
Shreyash
