### ISSUE TITLE
Advanced demo like animations with Fragments

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#49]
Hello.

I want to implement similar effect as in Advanced Demo with Fragments.

The problem is, when I have layout:

Activity:
```xml
<CoordinatorLayout>
	<!--Toolbar wrapped with AppBarLayout -->
	<include layout="@layout/toolbar_appbar"/>

	<RelativeLayout>
		<FrameLayout /> <!--Fragment container  -->
	</RelativeLayout>

</CoordinatorLayout>
```

Fragment:

```xml
<RelativeLayout>
	<RecyclerView />
	<RelativeLayout /> <!--Progress/Loading & Error Views -->

	<include layout="@layout/layout_photo_pager_no_toolbar.xml"/>
</RelativeLayout>
```

layout_photo_pager_no_toolbar.xml:
```xml
<merge>
    <View android:id="@+id/toolbarBack"/>

    <View android:id="@+id/pagerBackground"/> <!--black background -->

    <ViewPager android:id="@+id/pager"> <!--photo pager -->

    <Toolbar android:id="@+id/pagerToolbar"/>

    <TextView android:id="@+id/pagerTitle"/>
</merge>
```
ImageViews in RecyclerView items in Fragment, will animate to ViewPager items.

Black background and photo in layout_photo_pager_no_toolbar.xml won't cover the Toolbar (or other views, as BottomBar) in the Activity. It will only cover views in the Fragment.

The question is, how can I achieve Advanced Demo like effects in a similar layout as above? Covering all views?
Is there any way to animate view from RecyclerView in the Fragment, to ViewPager placed in the Activity?
Or is there any other solution you can suggest?

Thank you for your awesome library!

**Comment by alexvasilkov** [comment]
First of all, I don't think it is a good idea to have pager with images inside coordinator layout, I doubt it will work this way. So I suggest to move it outside.
Also it seems that toolbar should belong to fragment, so if you want to change fragments within activity just change them along with their respective toolbars.

Anyway, to implement it as in demo you just need to have access to both RecyclerView and to ViewPager. ViewPager can be passed from activity (or from other fragment) to target fragment by activity. There will be some work to orchestrate this relations especially when activity is restored from saved state, but it should not be very hard. Or you can have a public method to get ViewPager from activity, as long as you use fragment from single activity it should not be a big deal.

**Comment by alashow** [comment]
Thanks for the reply.

I didn't realize that having access to ViewPager from fragment is enough for animations. I will try to implement it that way, but for some reason, I think it won't work.

Thanks for the suggestion about moving the pager outside CoordinatorLayout. In one of my apps, I use it that way and it works (ViewPager is direct child of CoordinatorLayout).

**Comment by alexvasilkov** [comment]
Hm, actually in this case pager will cover initial toolbar and bottom bar which may not be good for animations.

So what you want is to have recycler view on the bottom, then full screen pager layer (with background), then layer with initial toolbar and bottom bar, and then pager's toolbar as overlay. In this case you can gradually fade initial toolbar and bottom bar out and fade in pager's toolbar.

If your bottom bar is static then you can keep it in activity and just add bottom margin for recycler view in fragment, so your list will be above the bar but pager will be underneath.

Same can be done with toolbar, though I still think it is better to keep it in fragment.

So your overall hierarchy may be like this:

* Activity with bottom bar
* Fragment, placed underneath bottom bar in activity.
* In fragment you will have:
  * Recycler view with bottom margin == height of bottom bar in activity and top padding == height of toolbar.
  * Pager on top of recycler view, without margins.
  * Toolbar for list mode.
  * Toolbar for pager mode.

If you want to use coordinator layout to animate toolbar when recycler view is scrolled then it can be a problem. But if you said that placing pager inside coordinator layout worked for you then it can be an option.

**Comment by alashow** [comment]
Thank you for your suggestions.

Placing the toolbar in fragment may be a problem. Because the toolbar in MainActivity is "shared" by other fragments in Activity (which is being controlled by bottom bar). Using toolbar separately will require using separate toolbar in other fragments too.

>Hm, actually in this case pager will cover initial toolbar and bottom bar which may not be good for animations.

What is wrong with it? Fading in/out only pager layer (pager & background & toolbar etc.) seems better to me, no?

**Comment by alexvasilkov** [comment]
Images which were partly scrolled underneath toolbar or bottom bar will pop up when animation will start, since pager will be drawn above them. If it is not a problem for you then you can do it the simplest way just by overlaying pager above both toolbar and bottom bar. Otherwise you may want to combine the layout in the way suggested above. You can place toolbar in activity as long as layers order is correct (recycler -> pager -> toolbar & bottom bar -> pager's toolbar).

**Comment by alashow** [comment]
It doesn't look that bad, so yeah, it's not a problem. I implemented it, and it works very smooth.

Implementation was pretty easy. As you said, I just needed access to ViewPager from Fragment.

Thanks for help!

Closing.
