### ISSUE TITLE
What happended to MovementBounds.getMovementAreaWithGravity

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#52]
What happened to this function? Is it still available somewhere under another name or so? I can't find  `getMovementAreaWithGravity` anywhere anymore...

**Comment by alexvasilkov** [comment]
`MovementBounds` class was in internal package, so I considered it as a "free to break" API.
Now it is moved to `com.alexvasilkov.gestures.utils.GravityUtils#getMovementAreaPosition(...)` and will be treated as public API.

**Comment by MFlisar** [comment]
OK thanks.

**Comment by alexvasilkov** [comment]
What's the problem with built in crop?

**Comment by MFlisar** [comment]
I just checked it, actually nothing, it's completely the same as my function. Seems to be a relict in my code...

But I need the above method in a second place as well, for increasing zoom via double tap via a custom factor and keeping the image centered around it's currently displayed center

**Comment by alexvasilkov** [comment]
Ok, setting different max zoom for double tap is on my TODO list.

**Comment by MFlisar** [comment]
If you need it, here's my method (it increases zoom by factor 3 until the max zoom is reached, then it jumps back to initial default zoom and so on...):

	@Override
	public boolean onDoubleTap(@NonNull MotionEvent event)
	{
		State state = imageView.getController().getState().copy();
		float zoom = state.getZoom();
		float maxZoom = imageView.getController().getSettings().getMaxZoom();
		if (zoom == maxZoom)
			zoom = imageView.getController().getStateController().getEffectiveMinZoom();
		else
		{
			if (zoom < maxZoom)
				zoom *= 3f;
			if (zoom > maxZoom)
				zoom = maxZoom;
		}
		Rect area = new Rect();
		GravityUtils.getMovementAreaPosition(imageView.getController().getSettings(), area);
		state.zoomTo(zoom, -area.left + area.width() / 2f, -area.top + area.height() / 2f);
		imageView.getController().animateStateTo(state);
		return true;
	}

**Comment by alexvasilkov** [comment]
Actually in your method you can just get position of supplied touch even and scale image around this point, scaling around center of the movement area may not work well.
