### ISSUE TITLE
OnExitListener

### ISSUE THREAD

**Issue by MFlisar** [alexvasilkov/GestureViews#53]
Is this possible?

I have view based layouts and navigations (no fragments) so normally I do following:

* navigate back in my views
* starts the back animation and update my navigation level state

The new feature requests from me, that I tell my navigation logic, that the user is exiting the current app level, therefore I would need to find out, that the user has started an exit animation himself, so that I can update depending navigation states.

Would you mind adding a listener for this? It would be enough to be able to listen to this event and get notified, when the back animation has finished. The `PositionUpdateListener` is not enough for me currently, because I can't distinct between a user started animation via a close gesture or a programmatically started animation via `animator.exit(true)`...

**Comment by alexvasilkov** [comment]
I think that exiting full mode by touch (with exit gesture) and by back button (with `ViewPositionAnimator#exit(true)`) should both be treated as exit by user.

Anyway, if you want to check that current exit animation was triggered by exit gesture you can do it indirectly by checking `ViewPositionAnimator#getToPosition() < 1f` inside `PositionUpdateListener`.
Note though, that at the point `position == 0f && isLeaving == true` `ViewsTransitionAnimator#getToView()` will return `null`, so you will need to cache flag indicating that current animation was started by exit gesture somehow.

**Comment by MFlisar** [comment]
Thanks, that helps already
