### ISSUE TITLE
Using crop(), black background is default when viewport is not completely filled

### ISSUE THREAD

**Issue by Ketn** [alexvasilkov/GestureViews#55]
On crop(), the default background for empty/transparent area of the viewport becomes black. Any way to avoid that or having another default color for transparent like White?

**Comment by alexvasilkov** [comment]
I just tried to crop png with transparent background and it works just fine. So maybe be something wrong with your image, or bitmap compression algorithm?

![device-2017-02-05-220556](https://cloud.githubusercontent.com/assets/3725494/22627194/97af682c-ebf0-11e6-8d8f-323cfa8fca1d.png)

![device-2017-02-05-220616](https://cloud.githubusercontent.com/assets/3725494/22627196/a11a7618-ebf0-11e6-825e-9d16456c9df2.png)

**Comment by GrindingOgre** [comment]
I think he is referring about this: 

If i load an image inside the GestureImageView, like in the picture:
![Screenshot_1604661838](https://user-images.githubusercontent.com/15261294/98361119-40561d00-202b-11eb-9e6d-108e2cc7dc37.png)

When i call crop(), the results is becoming this:

![Screenshot_1604661844](https://user-images.githubusercontent.com/15261294/98361075-2b798980-202b-11eb-9807-cb13b456d87c.png)

As you can see, the image has been cropped with those black bars to fill the gap left from the image. Is it possible to force a crop not with the View height and width, but only with the real content?

at the moment, i've set up the GestureImageView with these settings: 
`
            .setMaxZoom(5f)
            .setDoubleTapZoom(-1f)
            .setPanEnabled(true)
            .setZoomEnabled(true)
            .setDoubleTapEnabled(true)
            .setRotationEnabled(false)
            .setRestrictRotation(true)
            .setOverscrollDistance(0f, 0f)
            .setOverzoomFactor(7f)
            .setFillViewport(true)
            .setFitMethod(Settings.Fit.INSIDE)
            .setGravity(Gravity.CENTER)
            .setBoundsType(Settings.Bounds.INSIDE)
`

**Comment by alexvasilkov** [comment]
You should not fit the image INSIDE actually.

It is recommended to use CropAreaView, please follow this simple example: https://github.com/alexvasilkov/GestureViews/blob/master/sample/src/main/java/com/alexvasilkov/gestures/sample/ex/image/crop/ImageCropActivity.java

Or at least use setFitMethod(Settings.Fit.OUTSIDE) in your code.

**Comment by GrindingOgre** [comment]
I'm in need of that behavior, but fortunatelly, since your gesture view consider the "black" area as transparent (Color.TRANSPARENT or 0), i've wrote some code to actually crop out the transparent area. That way (if the image is not rotated), i can take only the requested part. That method can be optimized a lot, and can even consider the rotation if wrote differently.

I can surely make some other checks to avoid bad behaviors, but this method can trim the transparent area away from a bitmap.

```
fun Bitmap.trim(): Bitmap {
    var top = -1
    var left = -1
    var bottom = -1
    var right = -1

    for (x in 0..(width / 2)) {
        if (left == -1 && Color.TRANSPARENT != getPixel(x, height / 2)) {
            left = x
        }
        if (right == -1 && Color.TRANSPARENT != getPixel((width - 1) - x, height / 2)) {
            right = width - x
        }
        if (left >= 0 && right >= 0) {
            break
        }
    }
    for (y in 0..(height / 2)) {
        if (top == -1 && Color.TRANSPARENT != getPixel(width / 2, y)) {
            top = y
        }
        if (bottom == -1 && Color.TRANSPARENT != getPixel(width / 2, (height - 1) - y)) {
            bottom = height - y
        }
        if (top >= 0 && bottom >= 0) {
            break
        }
    }
    left = if(left >= 0) left else 0
    top = if(top >= 0) top else 0
    right = if(right >= 0) right else 0
    bottom = if(bottom >= 0) bottom else 0

    return Bitmap.createBitmap(this, left, top, right - left, bottom - top).also {
        this.recycle()
    }
}
```

In case i have some free time, i'll edit this method to make it consider even rotated images and to avoid exceptions.

BTW, thanks a lot for your lib, I love it so much!
