### ISSUE TITLE
Use requestDisallowInterceptTouchEvent() to properly coordinate touch events

### ISSUE THREAD

**Issue by Saketme** [alexvasilkov/GestureViews#60]
Hey alex, thanks for this fastastic library. I noticed that neither `GestureImageView`/`FrameView` call `requestDisallowInterceptTouchEvent()` when they start consuming events. This is bad because they currently don't work well with nested Views that support gestures. 

Since I'm using this library in one of my projects, I'd be happy to send a PR if you can guide me :)

**Comment by alexvasilkov** [comment]
Hi Saket, it is an old ticket, but could you please share your use case? I'm not sure I understand what you're trying to achieve, do you have something like a `ScrollView` inside `GestureFrameLayout`?

**Comment by Saketme** [comment]
Sure. I have a Layout that is dismissisble using a vertical swipe gesture. The layout looks like this:

<ViewPager>
  <SwipeDismissibleLayout>
    <GestureImageView />
  </SwipeDismissibleLayout>
</ViewPager>

`GestureViews` assumes that it'll only be used with ViewPagers and there won't be any layout in the middle that can also interact with touch events. Does this make sense, alex?

**Comment by alexvasilkov** [comment]
Thanks, and what do you expect from `GestureImageView` in this case?
If it will call `requestDisallowInterceptTouchEvent(true)` on touch then `SwipeDismissibleLayout` will not have a chance to handle touches itself.
In this case I think `SwipeDismissibleLayout` should decide itself whether he wants to pass events to its child or not in `onInterceptTouchEvent` method.

BTW, starting from [v2.2.0](https://github.com/alexvasilkov/GestureViews/releases/tag/v2.2.0) exit gesture was added to the library (using vertical swiping and zooming out).

**Comment by Saketme** [comment]
I'm already overriding `onInterceptTouchEvent()` in my layout, but if I can recall correctly, `GestureImageView`'s direct sending of events to the ViewPager, bypassing any layout in the middle was the problem.

I'm also aware of the exit gesture, but my usecase was slightly different so I implemented a custom one. :)

**Comment by alexvasilkov** [comment]
Yeah, I see, `GestureImageView` will pass scrolling events directly to `ViewPager` bypassing other layouts in the middle.

But what is your expected behavior here? If I'll call `requestDisallowInterceptTouchEvent ()` method of direct parent on touch down, then you will not be able to handle touch events in parent layout anymore. Do you want this `requestDisallowInterceptTouchEvent ()` to be called only if image can be panned and not called otherwise, so you can handle events yourself? I guess you can do this trick yourself as well from within `SwipeDismissibleLayout`.

Just curious, how exit gesture should work in your usecase? :)

**Comment by Saketme** [comment]
> Do you want this requestDisallowInterceptTouchEvent () to be called only if image can be panned and not called otherwise...

Yes! Only when the user starts scrolling and the image can be panned further and not on touch down.

> I guess you can do this trick yourself as well from within SwipeDismissibleLayout.

Right, I can but it involves me manually checking if the image can be panned further. 

> Just curious, how exit gesture should work in your usecase? :)

**Comment by alexvasilkov** [comment]
> Yes! Only when the user starts scrolling and the image can be panned further and not on touch down.
> Right, I can but it involves me manually checking if the image can be panned further.

That's not very clear actually. You may want to start exit gesture (swipe up/down) in several different cases:
* Image is not scrollable in vertical direction
* Image is not scrollable in any direction
* Image cannot be scrolled further in particular direction (reached the edge)

I cannot really decide for you how you want to achieve this, so I think it is better if you'll control it yourself. It will also be much cleaner than relying on `requestDisallowInterceptTouchEvent` logic.

**Comment by Saketme** [comment]
Right so in all these cases, `GestureImageView` will not disallow the parent from intercepting touch events so that the parent can continue handling the gesture. If the user wants enable exit gesture in `GestureImageView`, then it can choose to disallow the parent when an exit is possible.

> so I think it is better if you'll control it yourself

But there is no easy way. Ideally, `GestureImageView` should receive touch events without getting intercepted by the parent first so that it can check if it can be panned further. If it can be panned, send a signal to all parents to disallow intercepting touch events. This is how ideally it should block `ViewPager` from scrolling horizontally. 

By intercepting touch events in my container, before they reach `GestureImageView`, I will have to manually check if the image can be panned further, which I do not want to do. It's not the responsibility of the container.

**Comment by alexvasilkov** [comment]
> But there is no easy way.

There is no easy way no matter on which side it is implemented. But as I said, I cannot decide for you which of 3 ways you want your exit gesture to work, so I should not prevent you from applying your own logic by disallowing interception.

> By intercepting touch events in my container, before they reach GestureImageView, I will have to manually check if the image can be panned further, which I do not want to do. It's not the responsibility of the container.

Actually I'm not sure how hard it is to implement. You basically need to implement `onInterceptTouchEvent` and on each event you should check if image can be panned:
```Java
State state = image.getController().getState();
RectF area = new RectF();
image.getController().getStateController().getMovementArea(state, area);
```
Where area rect is a react in which x and y coords of state object can change.
If Image cannot be panned then just intercept touches and do whatever you want.

> This is how ideally it should block ViewPager from scrolling horizontally. The current implementation of sending events directly to the ViewPager is hacky.

I would be happy if it was so easy, but it's not. You can check how laggy it works in [PhotoView](https://github.com/chrisbanes/PhotoView) (e.g. try to zoom image in a bit and then scroll image until it should switch to `ViewPager` scroll), also check [their problem](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups) with parent ViewGroup.

**Comment by Saketme** [comment]
> Actually I'm not sure how hard it is to implement. You basically need to implement onInterceptTouchEvent and on each event you should check if image can be panned

True, but I feel that this is not the responsibility of the parent and this is why `onRequestDisallowIntercept()` exists.

> I would be happy if it was so easy, but it's not. You can check how laggy it works in PhotoView (e.g. try to zoom image in a bit and then scroll image until it should switch to ViewPager scroll), also check their problem with parent ViewGroup.

Ah, I did not imagine that. Got it. Using a custom ViewPager seems to be the easier way for me right now. :)

**Comment by alexvasilkov** [comment]
Ok, I agree with you that we should really call `requestDisallowInterceptTouchEvent`, please check [this pull request](https://github.com/alexvasilkov/GestureViews/pull/87/files), does it work for you as you expect? Note that I have to call it on DOWN event, since otherwise ViewPager may intercept touches on the very first MOVE event for a quick swipe gesture.

**Comment by Saketme** [comment]
Yep, it does :)

**Comment by alexvasilkov** [comment]
Thanks for feedback, v2.3.2 is released.
