### ISSUE TITLE
set zoom level to default

### ISSUE THREAD

**Issue by pro100svitlo** [alexvasilkov/GestureViews#63]
hi!
First of all - thanks :)

I think it will be great add some feature like setImageDefaultZoomLevel.
example: I am using viewPage. I zoom first image, than swipe to second. than swipe back to first
current behaviour: first image still zoomed
expected behaviour: first image will be with default zoom level

so i offer to add new feature - set image to default zoom level.
it also can be default behaviour if image lost it focus.

**Comment by alexvasilkov** [comment]
In its core library does not really now if image is on current page of `ViewPager` or not. I'm not eager to add this awareness into the `GestureImageView`.

So there are two options:
1. If you use enter / exit animations using:
```
GestureTransitions.from(...).into([pager]).enter(...);
-or (from old lib version)-
new ViewsTransitionBuilder().fromRecyclerView(...).intoViewPager(...).build().enter(...);
```
then image will be zoomed to default level automatically.

2. If you're only using `GestureImageView` in ViewPager then you can reset state manually using `VeiwPager`'s `OnPageChangeListener`:

```
    @Override
    public void onPageScrollStateChanged(int state) {
        if (state == ViewPager.SCROLL_STATE_IDLE && currentPage != viewPager.getCurrentItem()) {
            PaintingsPagerAdapter adapter = (PaintingsPagerAdapter) viewPager.getAdapter();
            if (adapter.getViewHolder(currentPage) != null) {
                PaintingsPagerAdapter.getImage(adapter.getViewHolder(currentPage))
                        .getController().resetState();
            }

            currentPage = viewPager.getCurrentItem();
        }
    }
```
