### ISSUE TITLE
Double Tap not working properly

### ISSUE THREAD

**Issue by rishabhja** [alexvasilkov/GestureViews#68]
After I zoom in more than double tap limit, tapping again leads to zooming out to double tap limit and then to 1x zoom

**Comment by alexvasilkov** [comment]
Yep, this is how it is implemented now. What's your expected behaviour?

**Comment by rishabhja** [comment]
On double tap, it should reset to original size instead

**Comment by alashow** [comment]
I agree that double tapping should reset zoom level.

**Comment by alexvasilkov** [comment]
Yeah, good point, will fix it

**Comment by rishabhja** [comment]
Is it done?

**Comment by rishabhja** [comment]
Any progress?

**Comment by alexvasilkov** [comment]
Fixed in v2.3.1
