### ISSUE TITLE
Pre-set image before animation logic

### ISSUE THREAD

**Issue by alashow** [alexvasilkov/GestureViews#71]
I have a check before setting drawable from `fromView` to `toView`. 

```java
mAnimator.setReadyListener(id->{
   ImageView from = (ImageView) mAnimator.getFromView();
   ImageView to = (ImageView) mAnimator.getToView();

   boolean thumbLoaded = itemList.get(id).getPhoto().isThumbnailLoaded();
   if (to.getDrawable() == null && thumbLoaded) {
        to.setImageDrawable(from.getDrawable());
   }
});
```

After e5e14f96cfaa82aa8f8285643148d170dc7108c9, it looks like I can't customize logic of pre-setting.

**Comment by alashow** [comment]
I think a simple toggle for enabling/disabling pre-setting solve the problem.
Or maybe synchronous callback before trying to pre-set, something like this:
```java
boolean shouldPreset = true;
if (shouldPresetListener != null) {
    shouldPreset = shouldPresetListener.should();
}
if (shouldPreset && getFromView() instanceof ImageView && getToView() instanceof ImageView) {
    // Pre-setting 'to' image with 'from' image to prevent flickering
    ImageView from = (ImageView) getFromView();
    ImageView to = (ImageView) getToView();
    if (to.getDrawable() == null) {
        to.setImageDrawable(from.getDrawable());
    }
}
```

**Comment by alexvasilkov** [comment]
Hm, not sure I understand your problem.
If you don't want default behaviour you can set drawable back to null:

```
if (to.getDrawable() == null && thumbLoaded) {
    to.setImageDrawable(from.getDrawable());
} else {
    to.setImageDrawable(null);
}
```

In your code from first comment.

**Comment by alashow** [comment]
But default behavior will be executed anyway? Which will take extra ms for doing that, right?

**Comment by alexvasilkov** [comment]
Yes, but `to.setImageDrawable(from.getDrawable());` is pretty cheap. It takes around 0.4 ms on average on Nexus 5 Android 6.0.

**Comment by alashow** [comment]
What if bitmaps are big?
Or if one doesn't want this behavior by default?

Toggle option for this behavior would be useful.

**Comment by alexvasilkov** [comment]
It does not depend on bitmaps sizes. And bitmaps are already loaded into memory, so no memory pressure here as well.

If you don't want this behavior you can override it as suggested in my first comment. I don't really like hacky solution with listener.

**Comment by alashow** [comment]
I see.
By toggle, I didn't mean the solution with a listener. But something like this:
```java
private boolean shouldPresetImage = true;

// getter/setter

if (shouldPresetImage && getFromView() instanceof ImageView && getToView() instanceof ImageView) {
```

Closing for now.

Thanks!
