### ISSUE TITLE
MinZoom 

### ISSUE THREAD

**Issue by jateenaero** [alexvasilkov/GestureViews#72]
Hello Sir,

I am trying set minZoom for my GestureImageview, So that user can Zoomout beyond viewport. Any help? there is no such setting.

**Comment by alexvasilkov** [comment]
Nope, there is no such option now unfortunately. But what is your use case, why may you need to set this value yourself?

BTW, you can try to set movement area to a smaller size than the view itself, in this case image will start smaller than viewport:
```
getController().getSettings().setMovementArea(width, height);
```
You can check it in `PhotoCropActivity` in sample app.
