### ISSUE TITLE
onclicklisteners not working

### ISSUE THREAD

**Issue by supercoder123** [alexvasilkov/GestureViews#74]

**Comment by alexvasilkov** [comment]
Can't help if you will not provide more details about your issue.

**Comment by supercoder123** [comment]
i have a full screen imageview place inside a relative layout...i tried using gesture image view but the on click listener was not  working .So i replaced it with a normal Image View and then the on click listener works. But it's useless as i need zoom and pan capabilites

**Comment by alexvasilkov** [comment]
Please check "Listeners" sections of [Usage wiki](https://github.com/alexvasilkov/GestureViews/wiki/Usage).

In short you just need to use `setOnGesturesListener(OnGestureListener listener)` method and override listener's `onSingleTapUp` method.

**Comment by supercoder123** [comment]
can you give me an example

**Comment by alexvasilkov** [comment]
```java
gestureView.getController().setOnGesturesListener(new SimpleOnGestureListener() {
    public boolean onSingleTapUp(MotionEvent event) {
        // Do you stuff here
        return true; // return true if event was consumed, false otherwise.
    }
})
```

**Comment by supercoder123** [comment]
Thanks man ...You are awesome.. :) Thanks for the quick reply ...You should consider adding that snippet to the wiki
