### ISSUE TITLE
Advanced demo resources

### ISSUE THREAD

**Issue by jitendra1607** [alexvasilkov/GestureViews#76]
How can i use my server image resources,what is type of json data?.please show me webserver image fetching used in this app.thank you

**Comment by jitendra1607** [comment]
I am beginner in android.i want to use advanced demo activity.please show me resource,so that i can configure it for my use.

**Comment by alexvasilkov** [comment]
Have a look at [Retrofit](http://square.github.io/retrofit/) + Gson, this is kinda industry standard now to load and parse the data.

Other than that, your app implementation is out of scope of this library, so please use other resources to find a help (like StackOverflow), here I can only help you with the library usage itself.
