### ISSUE TITLE
Add marker

### ISSUE THREAD

**Issue by neestell** [alexvasilkov/GestureViews#77]
Hello, thanks for the flexible and stable library. Is there a way to add an image marker to specified position of any bitmap?

**Comment by alexvasilkov** [comment]
There is no out of the box support for this, but you can do it yourself with a bit of math, I created a simple example of how it can be achieved: https://gist.github.com/alexvasilkov/543c9451932e12859ed221c7cd3ad19e

**Comment by neestell** [comment]
Thanks! It works as expected!

**Comment by a2203611** [comment]
我也遇到了这个问题  您给的这个链接失效了 请问我改该怎么将图像标记添加到任何位图的指定位置

（https://gist.github.com/alexvasilkov/543c9451932e12859ed221c7cd3ad19e）
