### ISSUE TITLE
Open basic animation

### ISSUE THREAD

**Issue by fedeamura** [alexvasilkov/GestureViews#8]
how implement it? i dont get it.

i use:

                mImageView.getPositionAnimator().enter(viewAnim, true);

and i get:

java.lang.NullPointerException: Attempt to invoke virtual method 'void com.alexvasilkov.gestures.GestureController.resetState()' on a null object reference

**Comment by alexvasilkov** [comment]
Looks like an issue.
Please try using latest version (2.0.3), do you still have this problem?
If yes, could you provide full stacktrace and more info on your usage?

**Comment by alexvasilkov** [comment]
So, does it works for you in latest version or you still have this issue?

**Comment by fedeamura** [comment]
Sorry for the delay.
Still no work :/

Tomorrow i will post a full stacktrace. Thanks.

**Comment by fedeamura** [comment]
With the 2.0.3 version, its work.

But im having troubles with the scale.

I record a video:
https://drive.google.com/file/d/0B1jx6rK5CDqTZ1ZKVks0YlNmckU/view?usp=sharing

**Comment by alexvasilkov** [comment]
Most probably you are using Glide which automatically crops bitmaps to fit view, and this breaks logic that determines start image position. To fix it try loading view `.into(new GlideDrawableImageViewTarget(image))` instead of `.into(image)`.

**Comment by fedeamura** [comment]
im using UniversalImageLoader. U know hoy can i fix it?

**Comment by fedeamura** [comment]
y try with glide.... still not working

**Comment by alexvasilkov** [comment]
Sorry, I have never used UIL before, can't say if there any issues with it.  
But anyway, in latest version I added logic to center start and end images in case them have different aspect ratio, so it should work even if your thumbnail image is square. Isn't it work for you in latest version (2.1.0 or 2.1.1)? Can you provide start and end images and maybe video of the issue you have?

**Comment by alexvasilkov** [comment]
Any info here, does it work for you in v2.1.1?
