### ISSUE TITLE
viewpager中的单击应该如何设置

### ISSUE THREAD

**Issue by hfg5961107** [alexvasilkov/GestureViews#80]
请问一下我要如何设置viewpager中图片的单击事件？双击缩放，但是我希望能够单击退出。该如何操作？谢谢

**Comment by hfg5961107** [comment]
为GestureImageView设置onclick事件不会被触发。

**Comment by alexvasilkov** [comment]
I don't really understand Chinese, so it would be better if we'll use English here. Anyway, it seems like you are looking for `controller.setOnGesturesListener(...)` method, where you can listen for `onSingleTapUp()` method call.

**Comment by hfg5961107** [comment]
sorry,my english is poor，I used onSingleTapUp() method was succeed, but doubleclick was don't be triggered 
 
------------------ Original ------------------
From: "Alex Vasilkov"; 
Date: 2017年8月1日(星期二) 晚上8:23
To: "alexvasilkov/GestureViews"; 
Cc: "hfg5961107"; "Author"; 
Subject: Re: [alexvasilkov/GestureViews] viewpager中的单击应该如何设置 (#80)

 

I don't really understand Chinese, so it would be better if we'll use English here. Anyway, it seems like you are looking for controller.setOnGesturesListener(...) method, where you can listen for onSingleTapUp() method call.

**Comment by alexvasilkov** [comment]
If you need to detect double click along with single click then you should use `onSingleTapConfirmed` instead of `onSingleTapUp`. It will be triggered with a small delay, but it will make it possible do distinguish between single and double tap, this is how Android's gestures detector works.

**Comment by xanahopper** [comment]
Thanks for you library and this answer. It solved my problem.
