### ISSUE TITLE
how do I center image? 

### ISSUE THREAD

**Issue by angelkoh** [alexvasilkov/GestureViews#81]
Is it possible to center the loaded image if I am using match_parent for both the Width and Height?
Currently, it defaults to the top of the parent.
I noticed that portrait images are centered horizontally, but landscape images are not centered vertically.

    <com.alexvasilkov.gestures.views.GestureImageView 
                    android:id="@+id/view_main_image"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:padding="8dp"  />

setting layout_gravity and gravity don't seem to have any effects.

**Comment by angelkoh** [comment]
This can be achieved by 
getController().getSettings().setGravity(Gravity.CENTER);

**Comment by alexvasilkov** [comment]
Hm, `Gravity.CENTER` should be default setting, so you don't need to specifically set it unless you already set it to a different value somewhere else.
