### ISSUE TITLE
Animate Image from old state to new one

### ISSUE THREAD

**Issue by neestell** [alexvasilkov/GestureViews#83]
Hello, Alex
Is there a way to animate an image with rotation using a custom pivot. In current implementation an image rotates from translate values x1, y1 to x2, y2 of State class.

**Comment by alexvasilkov** [comment]
Not sure if I understand it correctly.
But if you just need to animate image from one state to another you can do next:

1. Copy current state `GestureController#getState()` using `State#copy()` method:
`State newState = controller.getState().copy();`
2. Rotate the sate using `State#rotateTo(...)` or `State#rotateBy(...)` methods:
`newState.rotateBy(angle, pivotX, pivotY);`
3. Use `GestureController#animateStateTo(State)` to animate to new state:
`controller.animateStateTo(newState);`

**Comment by neestell** [comment]
Yes, I did the same, but rotation does not perform anchored the PivotX, PivotY _during_ the animation.

**Comment by alexvasilkov** [comment]
You may probably need to disable bounds using `Settings#disableBounds()`. Otherwise controller will also try to keep final state within the bounds and animation will look different.

**Comment by neestell** [comment]
Disabling bounds does not help, I think the issue is linear interpolation between 2 matrices.

**Comment by alexvasilkov** [comment]
Yes, you are right. I added pivot point awareness for state animation: fba2dc31e, it will be part of next version, hopefully soon.

**Comment by neestell** [comment]
Awesome! The issue fully resolved!
Thanks a lot

**Comment by alexvasilkov** [comment]
Thanks for feedback, v2.3.2 is released.
