### ISSUE TITLE
Zooming in deforms text in TextView embedded in GestureFrameLayout

### ISSUE THREAD

**Issue by angelkoh** [alexvasilkov/GestureViews#84]
Text in TextView gets deformed when I zoom in far enough in a GestureFrameLayout.   

![giphy](https://user-images.githubusercontent.com/829758/29593162-5cce4d7c-87db-11e7-8503-e8ec4653dc0f.gif)

The following is the XML used 

        <com.alexvasilkov.gestures.views.GestureFrameLayout
            android:id="@+id/ll_gesture"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_gravity="center"
            android:gravity="center"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/font_name">

            <TextView
                android:id="@+id/tv_text"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textColor="@color/black"
                android:textSize="40sp" />

        </com.alexvasilkov.gestures.views.GestureFrameLayout>

**Comment by alexvasilkov** [comment]
Hm, cannot reproduce it in the sample app when setting max zoom to 30.
Anyway, it does not look like GestureFrameLayout's issue, because it just applies transformation matrix to canvas when drawing layout.

Do you have this issue with all fonts or only with this specific one? It maybe an issue with font rendering I guess.

**Comment by angelkoh** [comment]
you are correct. this was an issue with the font rendering, and not GestureFrameLayout's issue.

Specifically, the problem results from a bug in the hardware acceleration, resulting in a "Font size too large to fit in cache" error.

I resolved the issue by adding android:layerType="software" in my xml.

    <com.alexvasilkov.gestures.views.GestureFrameLayout
        android:id="@+id/ll_gesture"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_gravity="center"
        android:gravity="center"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/font_name">

        <TextView
            android:id="@+id/tv_text"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textColor="@color/black"
            android:layerType="software"
            android:textSize="40sp" />

    </com.alexvasilkov.gestures.views.GestureFrameLayout>
