### ISSUE TITLE
How can I keep the view at the location after the move?

### ISSUE THREAD

**Issue by ZhouKanZ** [alexvasilkov/GestureViews#86]
In my project , I need that view extended gestureImageView keep location after move ,  now  it will  retrun back to the position what i dont want ;
please tell me how to resolve it ?

**Comment by alexvasilkov** [comment]
Try disabling bounds restriction with:
`gestureImage.getController().getSettings().disableBounds()`
More settings can be found in [wiki](https://github.com/alexvasilkov/GestureViews/wiki/Settings).

**Comment by ZhouKanZ** [comment]
tks so much  !   I thinked i try the all setting but missing this  ><!!!
