### ISSUE TITLE
Animate an GestureImageView in a ScrollView to a full size GestureFrameLaoyt

### ISSUE THREAD

**Issue by nelsonalfo** [alexvasilkov/GestureViews#88]
Hi,

I have a image view with an image of some point in google maps. This image view is inside a scroolView. 

What I want to do is to make the zoom in gesture or the double tap gesture to show a full size FrameLayout that have the actual map with some buttons.

The questions is: it is posible to achive that using a GestureImageView that recive the gestures and showing a GestureFramentLayout with the map and the buttons? given that the GestureImageView will be in a ScrollView #

**Comment by alexvasilkov** [comment]
Hi, nope, there is no option to animate from GestureImageView to GestureFramentLayout, only from regular ImageView into GestureImageView.

In your case you may try to animate map view itself from one state to another. Or you can animate the image and then show map view above, but I doubt it will look good enough.
