### ISSUE TITLE
Error:A problem occurred configuring project ':library'.

### ISSUE THREAD

**Issue by Mzoirov** [alexvasilkov/GestureViews#89]
Just checked out your project into Android Studio, this happens when I try to sync the build. I haven't touched the code this is fresh clone.

**Comment by alexvasilkov** [comment]
Not very informative :)

What version of Android Studio do you use?

**Comment by Mzoirov** [comment]
Android Studio 2.3.3

**Comment by alexvasilkov** [comment]
Works fine for me. Note, that during import AS will ask you to update Gradle to v3.3, you should NOT do that since this version has breaking changes and I will first need to adapt project to these changes.

**Comment by Mzoirov** [comment]
Worked, Thanks a lot!
