### ISSUE TITLE
Rotating images in the code 

### ISSUE THREAD

**Issue by joyoyao** [alexvasilkov/GestureViews#9]
how Rotating images in the code

**Comment by alexvasilkov** [comment]
Try this:

    getController().getState().rotateTo/By(...);
    getController().update();

**Comment by joyoyao** [comment]
thanks

**Comment by joyoyao** [comment]
cannot  fill the Viewport  after done it,

**Comment by alexvasilkov** [comment]
Probably you need to zoom image out when rotating. Try to set very small zoom level, in this case lib will fit image into viewport.
