### ISSUE TITLE
Is there a way to programmatically trigger the double tap effect?

### ISSUE THREAD

**Issue by Edward608** [alexvasilkov/GestureViews#93]
I would like to trigger the double tap event when the user clicks on the view, I've tried to use a onTouchListener and animate to the state. I found the event passed to me have been applied with your own transformation matrix, leading to incorrect pivot when I use the event's x&y to set the controller's state.

Is there a way to get the event's x&y before transform? or some other way to do the same effect?
I want to programmatically zoom into the tap position, but the event coordinate didn't quite correct as the internal event coordinate

**Comment by Edward608** [comment]
Now I can get my desired effect with some tricks, I would like to know is there any way to disable gesture zoom while allowing programmatic zoom?
As I tried, when setting `disableZoom` to `true`, the view will automatically zoom out.

**Comment by alexvasilkov** [comment]
1. You can use `GestureController#setOnGesturesListener(...)` method with `SimpleOnGestureListener` to listen for `onDoubleTap()`. Just checked that touch event's coordinates work just fine: `end.zoomTo(targetZoom, event.getX(), event.getY())`.

2. Disabling zoom will really make the image zoom back, that is actually a bug and I just fixed it.
It will be available in next version (after current 2.4.0).

**Comment by Edward608** [comment]
@alexvasilkov The zoom back bug need to be fix ASAP, it's very disturbing and actually make the gesture control much more difficult.

I'm now experiencing a new issue that any other gesture will make the layout zoom out automatically, any idea it is the same issue or a new one?

**Comment by alexvasilkov** [comment]
Yes, looks like the same issue. Version [2.4.1](https://github.com/alexvasilkov/GestureViews/releases/tag/v2.4.1) including this fix is released now. Will take few hours before it will be available through maven central.

Let me know if it does not fix your issue.
