### ISSUE TITLE
In landscape orientation, full image is not shown

### ISSUE THREAD

**Issue by iamjaspreetsingh** [alexvasilkov/GestureViews#95]
In the option, Layouts in ViewPager when I change my screen orientation to landscape , full image is not shown and a part of it gets hidden. 
Please check .

**Comment by alexvasilkov** [comment]
Hm, sounds strange. I changed sample app quite a lot recently and I can't see any problems in this example now. Can you please check it again?

**Comment by iamjaspreetsingh** [comment]
It is working well in all cases except for layout in ViewPager option
I am sharing the screenshot. Please check 

(I have checked from the sample app on Playstore) 

![screenshot_2017-12-10-19-54-25-417_com alexvasilkov gestures sample](https://user-images.githubusercontent.com/30948046/33805955-880e0ee4-dde6-11e7-9de2-075f646c818b.png)

**Comment by alexvasilkov** [comment]
Aha, it is actually a correct behaviour. Image view in this sample uses "centerCrop" scale type, so there is no bug here.

**Comment by alexvasilkov** [comment]
To be clear, this image is not supposed to be fully shown, it is used as background.

**Comment by iamjaspreetsingh** [comment]
Oh, I got it. 
Is it meant only for landscape orientation ( as in potrait mode, it is showing full image) ?

**Comment by alexvasilkov** [comment]
Layout is absolutely the same, it is just a coincident, check other pages in sample example.

**Comment by iamjaspreetsingh** [comment]
Everything is working nicely. Good job!
