### ISSUE TITLE
Gif Support

### ISSUE THREAD

**Issue by vishalvaghani** [alexvasilkov/GestureViews#96]
it can possible to view GIF image with playing.
currently GIF image showing but not playing.

**Comment by alashow** [comment]
Are you sure this is because of GestureViews? Have you tested it without GestureViews?
Maybe you are loading your image wrong?

**Comment by alexvasilkov** [comment]
Gif animation works fine for me, I just replaced one of the images in sample app with animated gif and it just started playing as soon as it is shown (thanks to Glide).
Note that images handling itself is not handled by this library, you should use other libs (like Glide or Picasso) to load images, including gifs.
